import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..','v52-conscious-reality');
const sync=JSON.parse(fs.readFileSync(path.join(root,'src/sync-timing.json'),'utf8'));
const out=path.join(root,'public/audio');fs.mkdirSync(out,{recursive:true});
const d=Math.ceil(sync.durationSeconds+3),fadeOut=Math.max(0,d-14);
execFileSync('ffmpeg',['-y','-loglevel','error','-f','lavfi','-i',`sine=frequency=38:duration=${d}`,'-f','lavfi','-i',`sine=frequency=57:duration=${d}`,'-f','lavfi','-i',`anoisesrc=color=brown:duration=${d}:amplitude=0.006`,'-filter_complex',`[0:a]volume=0.0035,lowpass=f=120[a0];[1:a]volume=0.0018,lowpass=f=170[a1];[2:a]highpass=f=22,lowpass=f=700,volume=0.10[a2];[a0][a1][a2]amix=inputs=3,afade=t=in:st=0:d=7,afade=t=out:st=${fadeOut}:d=14,acompressor=threshold=-26dB:ratio=2:attack=40:release=600`,'-c:a','aac','-b:a','128k','-ar','48000',path.join(out,'bgm.m4a')]);
console.log(`V52 BGM ready: ${d}s`);
