import React from 'react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';

export type Beat={id:string;visual:string;narration:string;speech?:string};
const font='"Noto Sans CJK JP",sans-serif';
const C={paper:'#f2eee5',muted:'#a2a7ad',ink:'#040608',blue:'#7ba4c5',cyan:'#75c7c8',amber:'#d8ac64',red:'#bd625d',green:'#82a983',violet:'#9b89bd',pink:'#c989a3',grey:'#41484f'};
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const bn=(id:string)=>Number(id.replace(/\D/g,''))||0;
const p=(f:number,a=0,b=24)=>interpolate(f,[a,b],[0,1],clamp);
const lerp=(f:number,a:number,b:number,c:number,d:number)=>interpolate(f,[a,b],[c,d],clamp);

const Dust=()=>{const f=useCurrentFrame();return <>{Array.from({length:42},(_,i)=><div key={i} style={{position:'absolute',left:(i*173+Math.sin((f+i*9)/77)*42)%1920,top:(i*113+f*.09)%1080,width:2+(i%3),height:2+(i%3),borderRadius:30,background:C.paper,opacity:.03+(i%6)*.012}}/>)}</>};
const Scene=({children,tone='night'}:{children:React.ReactNode;tone?:'night'|'blue'|'warm'|'black'|'rose'})=>{const f=useCurrentFrame();const bg=tone==='blue'?'linear-gradient(145deg,#06131d,#102a37 57%,#020406)':tone==='warm'?'linear-gradient(145deg,#180e0b,#35231b 57%,#030303)':tone==='rose'?'linear-gradient(145deg,#160a10,#2c1822 55%,#040304)':tone==='black'?'#020304':'linear-gradient(145deg,#05070a,#12171c 57%,#030405)';return <AbsoluteFill style={{background:bg,color:C.paper,overflow:'hidden',fontFamily:font}}><AbsoluteFill style={{transform:`scale(${1.008+Math.sin(f/170)*.006})`}}>{children}</AbsoluteFill><Dust/><AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,transparent 30%,rgba(0,0,0,.25) 72%,rgba(0,0,0,.82) 100%)'}}/></AbsoluteFill>};
const Headline=({children}:{children:React.ReactNode})=><div style={{position:'absolute',left:105,top:70,right:105,fontSize:50,fontWeight:950,letterSpacing:.6,textShadow:'0 5px 26px rgba(0,0,0,.78)'}}>{children}</div>;
const Pill=({x,y,text,color=C.cyan,delay=0,scale=1}:{x:number;y:number;text:string;color?:string;delay?:number;scale?:number})=>{const f=useCurrentFrame();const q=p(f,delay,delay+22);return <div style={{position:'absolute',left:x,top:y,padding:'13px 22px',borderRadius:999,border:`2px solid ${color}66`,background:'rgba(4,8,12,.80)',fontSize:28,fontWeight:900,color,opacity:q,transform:`translateY(${(1-q)*18}px) scale(${(.94+.06*q)*scale})`}}>{text}</div>};
const Arrow=({x,y,w,angle=0,color=C.amber}:{x:number;y:number;w:number;angle?:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:7,background:color,transform:`rotate(${angle}deg)`,transformOrigin:'0 50%',boxShadow:`0 0 18px ${color}55`}}><div style={{position:'absolute',right:-2,top:-9,width:0,height:0,borderTop:'13px solid transparent',borderBottom:'13px solid transparent',borderLeft:`22px solid ${color}`}}/></div>;
const Face=({x,y,size=160,color=C.blue,ghost=false,smile=true}:{x:number;y:number;size?:number;color?:string;ghost?:boolean;smile?:boolean})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,width:size,height:size,borderRadius:'50%',background:`radial-gradient(circle at 42% 34%,${color},#11151a 74%)`,border:`5px solid ${color}88`,boxShadow:`0 0 35px ${color}55`,opacity:ghost?.45:1,transform:`translateY(${Math.sin((f+x)/50)*5}px)`}}><div style={{position:'absolute',left:size*.28,top:size*.38,width:size*.12,height:size*.08,borderRadius:20,background:C.ink}}/><div style={{position:'absolute',right:size*.28,top:size*.38,width:size*.12,height:size*.08,borderRadius:20,background:C.ink}}/><div style={{position:'absolute',left:size*.34,top:size*.66,width:size*.32,height:size*.14,borderBottom:smile?`5px solid ${C.paper}`:`5px solid ${C.red}`,borderRadius:'0 0 80px 80px'}}/></div>};
const Meter=({x,y,label,value,color=C.cyan}:{x:number;y:number;label:string;value:number;color?:string})=>{const f=useCurrentFrame();const w=lerp(f,5,45,0,value*6);return <div style={{position:'absolute',left:x,top:y,width:760}}><div style={{fontSize:31,fontWeight:900,marginBottom:12}}>{label}</div><div style={{height:28,borderRadius:20,background:'rgba(255,255,255,.08)'}}><div style={{width:w,height:'100%',borderRadius:20,background:color,boxShadow:`0 0 22px ${color}55`}}/></div></div>};

const FutureCity=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const b=bn(beat.id);return <Scene tone="rose"><Headline>{b===1?'美容がほぼ完成した未来':'街中が美男美女になったら？'}</Headline>{Array.from({length:14},(_,i)=>{const x=120+(i%7)*255,y=260+Math.floor(i/7)*310;return <Face key={i} x={x} y={y} size={150+(i%3)*10} color={[C.pink,C.cyan,C.amber,C.violet][i%4]}/>})}<div style={{position:'absolute',left:520,top:850,fontSize:48,fontWeight:950,opacity:.85+.15*Math.sin(f/20)}}>{b===1?'誰でも「かなり整った顔」へ':'ルッキズムは終わるのか？'}</div></Scene>};
const BeautyFloor=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>「顔がいい」は加点ではなくなる</Headline><div style={{position:'absolute',left:260,top:260,width:1400,height:520,borderRadius:45,border:'3px solid rgba(255,255,255,.13)',background:'rgba(255,255,255,.03)'}}><div style={{position:'absolute',left:120,top:300,width:1160,height:12,background:C.grey}}><div style={{position:'absolute',left:0,top:-38,fontSize:34,fontWeight:900}}>最低ライン</div><div style={{position:'absolute',left:lerp(f,0,70,100,900),top:-35,width:80,height:80,borderRadius:'50%',background:C.red,boxShadow:`0 0 30px ${C.red}88`}}/></div><div style={{position:'absolute',left:480,top:120,fontSize:76,fontWeight:950}}>美貌 = 前提条件</div></div><Pill x={690} y={825} text="ボーナス → 参加資格" color={C.red}/></Scene>};
const NewAxes=()=>{const axes=['身長','声','体型','知性','年収','職業','家柄','SNS'];return <Scene tone="blue"><Headline>美貌の次に、別の物差しが並び始める</Headline>{axes.map((t,i)=><Pill key={t} x={180+(i%4)*420} y={270+Math.floor(i/4)*240} text={t} color={[C.blue,C.cyan,C.green,C.amber,C.violet,C.red,C.pink,C.paper][i]} delay={i*5} scale={1.12}/>)}</Scene>};
const ThesisReveal=()=>{const f=useCurrentFrame();const q=p(f,0,40);return <Scene tone="black"><div style={{position:'absolute',left:190,right:190,top:290,textAlign:'center',fontSize:76,fontWeight:950,lineHeight:1.4,opacity:q,transform:`scale(${.94+.06*q})`}}>全員が美しい世界は<br/><span style={{color:C.red}}>「美しいだけでは価値がない世界」</span><br/>かもしれない</div></Scene>};
const TwoValues=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene><Headline>{b===6?'美しさには「絶対」と「相対」がある':'他人より魅力的である、という価値'}</Headline><div style={{position:'absolute',left:260,top:300,width:580,height:430,borderRadius:42,border:`3px solid ${C.cyan}66`,background:'rgba(8,20,24,.64)'}}><Face x={210} y={95} size={160} color={C.cyan}/><div style={{position:'absolute',left:120,right:120,bottom:55,textAlign:'center',fontSize:38,fontWeight:950}}>絶対価値</div></div><div style={{position:'absolute',left:1080,top:300,width:580,height:430,borderRadius:42,border:`3px solid ${C.red}66`,background:'rgba(24,9,11,.64)'}}><Face x={80} y={100} size={140} color={C.grey}/><Face x={340} y={75} size={190} color={C.red}/><div style={{position:'absolute',left:120,right:120,bottom:55,textAlign:'center',fontSize:38,fontWeight:950}}>相対価値</div></div></Scene>};
const HeightContext=()=> <Scene tone="blue"><Headline>同じ180cmでも「意味」は変わる</Headline><div style={{position:'absolute',left:220,top:260,width:650,height:560,borderRadius:35,border:'2px solid rgba(255,255,255,.13)'}}><Pill x={170} y={60} text="平均170cm" color={C.cyan}/><div style={{position:'absolute',left:120,bottom:70,width:100,height:350,background:C.grey}}/><div style={{position:'absolute',left:360,bottom:70,width:100,height:430,background:C.cyan}}/><div style={{position:'absolute',left:330,bottom:20,fontSize:34,fontWeight:900}}>180cm</div></div><div style={{position:'absolute',left:1050,top:260,width:650,height:560,borderRadius:35,border:'2px solid rgba(255,255,255,.13)'}}><Pill x={170} y={60} text="平均190cm" color={C.red}/><div style={{position:'absolute',left:120,bottom:70,width:100,height:460,background:C.red}}/><div style={{position:'absolute',left:360,bottom:70,width:100,height:430,background:C.cyan}}/><div style={{position:'absolute',left:330,bottom:20,fontSize:34,fontWeight:900}}>180cm</div></div></Scene>;
const ScarcityDilution=()=>{const f=useCurrentFrame();const count=Math.floor(lerp(f,0,80,10,100));return <Scene><Headline>希少性が消えると「美しい」の情報量も薄れる</Headline><div style={{position:'absolute',left:220,top:250,width:1480,height:560,display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:12}}>{Array.from({length:100},(_,i)=><div key={i} style={{borderRadius:'50%',background:i<count?C.cyan:C.grey,opacity:i<count?.9:.2,boxShadow:i<count?`0 0 12px ${C.cyan}55`:'none'}}/>)}</div><Pill x={690} y={840} text={`${Math.min(100,count)} / 100 が「美しい」`} color={C.cyan}/></Scene>};
const PositionalGood=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="warm"><Headline>{b===10?'価値の一部は「他人より上」にある':'全体が改善しても、順位競争は残り得る'}</Headline>{['高級住宅','名門校','会員制クラブ','美貌'].map((t,i)=><div key={t} style={{position:'absolute',left:190+i*420,top:320+i*55,width:300,height:220,borderRadius:32,border:`3px solid ${[C.amber,C.blue,C.violet,C.pink][i]}66`,background:'rgba(0,0,0,.35)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:36,fontWeight:950}}>{t}</div>)}<Arrow x={300} y={700} w={1260} color={C.red}/><Pill x={690} y={790} text="相対的位置が価値になる" color={C.red}/></Scene>};
const SelectionMachine=()=>{const f=useCurrentFrame();const x=lerp(f%150,0,149,150,1500);return <Scene tone="blue"><Headline>一つの物差しが死ぬと、次の物差しが起動する</Headline><Face x={x} y={460} size={150} color={C.cyan}/><div style={{position:'absolute',left:690,top:240,width:540,height:430,borderRadius:50,border:`4px solid ${C.red}66`,background:'rgba(3,10,14,.8)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:54,fontWeight:950}}>選別機</div>{['顔','身長','年収','知性'].map((t,i)=><Pill key={t} x={720+i*10} y={320+i*80} text={t} color={[C.grey,C.cyan,C.amber,C.violet][i]} delay={i*5}/>)}</Scene>};
const MicroFeatures=({beat}:{beat:Beat})=>{const b=bn(beat.id);const arr=b===13?['輪郭','身長','脚の長さ','声','肌質','年齢','表情','雰囲気']:['鼻の角度','歯の形','横顔','首の長さ','手','所作'];return <Scene tone="rose"><Headline>{b===13?'「美人か」から「どんな美人か」へ':'差が縮むほど、評価は細かくなる'}</Headline><Face x={760} y={320} size={400} color={C.pink}/>{arr.map((t,i)=>{const a=i/arr.length*Math.PI*2;return <Pill key={t} x={900+Math.cos(a)*620} y={500+Math.sin(a)*330} text={t} color={[C.cyan,C.amber,C.red,C.violet,C.green,C.paper][i%6]} delay={i*4}/>})}</Scene>};
const SocialCompare=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>絶対的な「美しさメーター」は存在しない</Headline><Face x={820} y={390} size={220} color={C.paper}/>{['友人','同僚','SNS','少し上の人'].map((t,i)=>{const a=f/80+i*Math.PI/2;return <Pill key={t} x={900+Math.cos(a)*530} y={500+Math.sin(a)*280} text={t} color={[C.blue,C.cyan,C.red,C.amber][i]}/>})}<div style={{position:'absolute',left:670,top:820,fontSize:36,fontWeight:900,color:C.muted}}>比較対象が変われば、自分の評価も変わる</div></Scene>};
const MovingAverage=()=>{const f=useCurrentFrame();const avg=lerp(f,0,90,60,90);return <Scene tone="blue"><Headline>平均が上がると「普通」も上がる</Headline><div style={{position:'absolute',left:250,top:690,width:1420,height:10,background:C.grey}}><div style={{position:'absolute',left:`${avg/100*100}%`,top:-270,width:12,height:280,background:C.red}}><div style={{position:'absolute',left:-80,top:-60,width:180,fontSize:34,fontWeight:950,color:C.red}}>平均 {avg.toFixed(0)}</div></div></div><div style={{position:'absolute',left:300,top:350,fontSize:82,fontWeight:950}}>昨日の90点</div><div style={{position:'absolute',right:300,top:350,fontSize:82,fontWeight:950,color:C.red}}>今日の普通</div></Scene>};
const DecimalRanking=({beat}:{beat:Beat})=>{const b=bn(beat.id);const vals=[90.1,90.4,90.7,91.2];return <Scene><Headline>{b===17?'差がなくなると「小数点」が必要になる':'誤差だった差が、順位を決め始める'}</Headline>{vals.map((v,i)=><div key={v} style={{position:'absolute',left:260+i*380,top:340-i*35,width:300,height:240,borderRadius:34,border:`3px solid ${[C.grey,C.blue,C.cyan,C.red][i]}77`,background:'rgba(5,9,13,.75)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:72,fontWeight:950,color:[C.paper,C.blue,C.cyan,C.red][i]}}>{v}</div>)}<Pill x={680} y={760} text="全員が90点なら、90点には情報量がない" color={C.amber}/></Scene>};
const DatingGrid=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="rose"><Headline>{b===19?'恋愛は「顔だけ」の市場ではない':'顔面格差が縮むと、別の格差が流れ込む'}</Headline><div style={{position:'absolute',left:220,top:250,width:1480,height:560,display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:24}}>{Array.from({length:18},(_,i)=><div key={i} style={{borderRadius:30,border:`2px solid ${i%3===0?C.cyan:C.pink}55`,background:'rgba(255,255,255,.04)',padding:18}}><Face x={0} y={0} size={100} color={i%2?C.pink:C.cyan}/><div style={{marginTop:120,fontSize:22,fontWeight:800}}>容姿 90<br/>学歴 {60+i}<br/>年収 {400+i*45}</div></div>)}</div></Scene>};
const AppFilters=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="black"><Headline>{b===21?'全員「あり」だと、次のフィルターが必要になる':'新しい順位表は、すぐ完成する'}</Headline><div style={{position:'absolute',left:260,top:250,width:520,height:600,borderRadius:50,border:'3px solid rgba(255,255,255,.16)',background:'rgba(255,255,255,.04)'}}><Face x={170} y={70} size={180} color={C.pink}/><div style={{position:'absolute',left:90,right:90,bottom:100,fontSize:38,fontWeight:950,textAlign:'center'}}>容姿 90</div></div><div style={{position:'absolute',left:980,top:250,width:700,height:600}}>{['身長 185cm','年収 1200万','海外大学','経営者'].map((t,i)=><Pill key={t} x={0} y={i*125} text={t} color={[C.cyan,C.amber,C.blue,C.red][i]} delay={i*6} scale={1.14}/>)}</div></Scene>};
const MinimumStandard=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="blue"><Headline>{b===23?'美貌が「加点」から「参加資格」へ':'一つ欠けたときだけ、目立つ'}</Headline>{['整った顔','きれいな肌','歯並び','スタイル'].map((t,i)=><div key={t} style={{position:'absolute',left:230+i*400,top:330,width:320,height:300,borderRadius:36,border:`3px solid ${i===3&&b===24?C.red:C.green}66`,background:'rgba(4,11,15,.68)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:35,fontWeight:950,color:i===3&&b===24?C.red:C.green}}>{t}<div style={{position:'absolute',bottom:30,fontSize:30}}>{i===3&&b===24?'不足':'当然'}</div></div>)}</Scene>};
const FloorCeiling=()=>{const f=useCurrentFrame();const floor=lerp(f,0,80,220,650);return <Scene tone="black"><Headline>平均が上がるほど、最低ラインも上がる</Headline><div style={{position:'absolute',left:300,right:300,top:220,bottom:200,borderLeft:'4px solid rgba(255,255,255,.3)',borderBottom:'4px solid rgba(255,255,255,.3)'}}><div style={{position:'absolute',left:0,right:0,bottom:floor-220,height:8,background:C.red,boxShadow:`0 0 30px ${C.red}77`}}><div style={{position:'absolute',left:30,top:-55,fontSize:34,fontWeight:950,color:C.red}}>最低条件</div></div></div></Scene>};
const RedQueen=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const b=bn(beat.id);return <Scene tone="rose"><Headline>{b===26?'赤の女王：同じ場所にいるため走り続ける':'全員が努力すると、順位は変わりにくい'}</Headline><div style={{position:'absolute',left:250,right:250,top:690,height:32,background:'repeating-linear-gradient(90deg,#3b2d34 0 80px,#1b1519 80px 160px)',backgroundPositionX:-f*8}}/><Face x={460} y={410} size={180} color={C.pink}/><Face x={1260} y={410} size={180} color={C.cyan}/><Arrow x={700} y={540} w={460} color={C.amber}/><Pill x={710} y={790} text={b===26?'周囲も同時に進化する':'美容 / 筋トレ / 服 / 収入 / SNS'} color={C.amber}/></Scene>};
const Treadmill=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>全員が速くなっても、相対順位は同じ</Headline>{[0,1,2].map(i=><div key={i} style={{position:'absolute',left:260,top:320+i*180,width:1400,height:22,background:'repeating-linear-gradient(90deg,#444 0 70px,#222 70px 140px)',backgroundPositionX:-(f*(5+i))}}><Face x={350+i*280} y={-100} size={120} color={[C.pink,C.cyan,C.amber][i]}/></div>)}<Pill x={710} y={850} text="絶対値 ↑　相対的位置 →" color={C.red}/></Scene>};
const Future2050=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="blue"><Headline>{b===29?'2050年：全員が「2020年代ならモデル級」':'それでも、3ミリの差で悩む'}</Headline><Face x={420} y={310} size={360} color={C.cyan}/><div style={{position:'absolute',left:980,top:260,width:650,height:500}}>{b===29?<><Pill x={0} y={60} text="昔の写真：普通" color={C.grey}/><Pill x={0} y={190} text="現在：全員モデル級" color={C.cyan}/></>:<><Pill x={0} y={30} text="鼻が3mm低い" color={C.red}/><Pill x={0} y={160} text="顔の余白が多い" color={C.amber}/><Pill x={0} y={290} text="目の角度が古い" color={C.violet}/></>}</div></Scene>};
const ZoomedFlaws=()=>{const f=useCurrentFrame();const z=lerp(f,0,90,1,3.2);return <Scene tone="rose"><Headline>差が消えると、欠点の解像度が上がる</Headline><div style={{position:'absolute',left:640,top:250,width:640,height:640,transform:`scale(${z})`,transformOrigin:'50% 50%'}}><Face x={180} y={160} size={280} color={C.pink}/><div style={{position:'absolute',left:330,top:280,width:25,height:25,borderRadius:'50%',background:C.red,boxShadow:`0 0 30px ${C.red}`}}/></div><Pill x={720} y={850} text="大きな差 → 微細な差へ" color={C.red}/></Scene>};
const RankingDesire=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>問題は「顔」より、順位づけの欲望かもしれない</Headline><div style={{position:'absolute',left:800,top:270,width:320,height:540,borderRadius:40,border:`4px solid ${C.red}88`,background:'rgba(255,255,255,.03)'}}>{Array.from({length:7},(_,i)=><div key={i} style={{position:'absolute',left:40,top:40+i*65,width:240,height:42,borderRadius:10,background:i===Math.floor((f/20)%7)?C.red:C.grey,opacity:.75}}/>)}</div><Pill x={390} y={400} text="顔" color={C.pink}/><Pill x={1300} y={400} text="別の指標" color={C.cyan}/><Arrow x={560} y={520} w={220} color={C.red}/><Arrow x={1120} y={520} w={220} color={C.red}/></Scene>};
const MetricMigration=()=>{const f=useCurrentFrame();const labels=['顔','身長','年収','大学','フォロワー','センス','希少性'];return <Scene tone="blue"><Headline>選別の物差しは、次の希少性へ逃げる</Headline>{labels.map((t,i)=>{const x=190+i*235;const y=680-Math.sin(i*.8)*220;return <React.Fragment key={t}><Pill x={x} y={y} text={t} color={[C.pink,C.cyan,C.amber,C.blue,C.red,C.violet,C.green][i]} delay={i*5}/>{i<labels.length-1&&<Arrow x={x+120} y={y+25} w={150} angle={-10+Math.sin(i)*20} color={C.paper}/>}</React.Fragment>})}<div style={{position:'absolute',left:690,top:850,fontSize:34,fontWeight:900,color:C.muted}}>評価軸が死ぬたび、新しい評価軸が生まれる</div></Scene>};
const CredentialParallel=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene><Headline>{b===34?'学歴でも起きた「評価軸の細分化」':'競争は消えず、階層が細かくなる'}</Headline>{['大卒','大学名','学部','大学院','資格','留学'].map((t,i)=><div key={t} style={{position:'absolute',left:180+i*280,top:650-i*70,width:230,height:95,borderRadius:18,background:'rgba(255,255,255,.05)',border:`2px solid ${[C.grey,C.blue,C.cyan,C.amber,C.violet,C.red][i]}77`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:30,fontWeight:950}}>{t}</div>)}<Arrow x={250} y={780} w={1300} angle={-18} color={C.red}/></Scene>};
const GodUpgrade=()=>{const f=useCurrentFrame();return <Scene tone="warm"><Headline>もし神様が、全員を美男美女にしたら</Headline><div style={{position:'absolute',left:720,top:180,width:480,height:220,borderRadius:'50%',background:'radial-gradient(circle,#fff6cf,#c9a762 45%,transparent 72%)',opacity:.75+.25*Math.sin(f/20)}}/><Arrow x={960} y={390} w={270} angle={90} color={C.amber}/>{Array.from({length:6},(_,i)=><Face key={i} x={260+i*260} y={610} size={145} color={[C.pink,C.cyan,C.amber,C.violet][i%4]}/>)}</Scene>};
const RankingReborn=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>数日後、順位表は復活する</Headline><div style={{position:'absolute',left:320,top:250,width:1280,height:560,borderRadius:35,border:'3px solid rgba(255,255,255,.15)',background:'rgba(255,255,255,.03)',padding:50}}><div style={{fontSize:52,fontWeight:950,marginBottom:35}}>MOST BEAUTIFUL 100</div>{Array.from({length:7},(_,i)=><div key={i} style={{height:55,margin:'10px 0',width:lerp(f,0,80,100,1100-i*90),background:[C.red,C.pink,C.cyan,C.amber,C.violet,C.blue,C.green][i],borderRadius:10,opacity:.8}}/>)}</div></Scene>};
const ImperfectionLuxury=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="rose"><Headline>{b===38?'完璧が普及すると、不完全さが希少になる':'人類は完璧を得て、不完全を買い戻す'}</Headline><Face x={340} y={340} size={300} color={C.cyan}/><Face x={1220} y={340} size={300} color={C.pink}/><div style={{position:'absolute',left:1380,top:465,width:30,height:30,borderRadius:'50%',background:C.red,boxShadow:`0 0 25px ${C.red}`}}/><Arrow x={720} y={500} w={420} color={C.amber}/><Pill x={720} y={680} text={b===38?'希少性：不完全さへ':'「あなたらしい非対称性を」'} color={C.amber}/></Scene>};
const StatusCycle=()=>{const f=useCurrentFrame();const items=['派手な高級品','大衆化','静かな高級品','さらに希少な記号'];return <Scene tone="warm"><Headline>地位財は、普及すると次の希少性へ移る</Headline>{items.map((t,i)=>{const a=f/100+i*Math.PI/2;return <Pill key={t} x={860+Math.cos(a)*500} y={500+Math.sin(a)*280} text={t} color={[C.red,C.grey,C.amber,C.violet][i]}/>})}<div style={{position:'absolute',left:830,top:450,fontSize:110,fontWeight:950}}>↻</div></Scene>};
const GlobalFeed=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="black"><Headline>{b===41?'比較対象は「近所」から「世界」へ':'アルゴリズムは「少し上」を無限供給できる'}</Headline><div style={{position:'absolute',left:620,top:180,width:680,height:740,borderRadius:70,border:'8px solid #24282d',background:'#090b0e',overflow:'hidden'}}>{Array.from({length:12},(_,i)=><div key={i} style={{position:'absolute',left:30+(i%3)*205,top:30+Math.floor(i/3)*170,width:170,height:145,borderRadius:20,background:'rgba(255,255,255,.04)'}}><Face x={20} y={10} size={100} color={[C.pink,C.cyan,C.amber,C.violet][i%4]}/><div style={{position:'absolute',right:12,bottom:12,fontSize:22,fontWeight:900}}>TOP {Math.max(.01,i*.03).toFixed(2)}%</div></div>)}</div></Scene>};
const NotNecessarilyHell=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="blue"><Headline>{b===43?'全員が美しくなること自体は、悪ではない':'問題は「選別」が消えるかどうか'}</Headline><div style={{position:'absolute',left:260,top:300,width:580,height:420,borderRadius:40,border:`3px solid ${C.green}66`,background:'rgba(10,25,14,.55)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:45,fontWeight:950,color:C.green,textAlign:'center'}}>露骨な容姿差別<br/>↓</div><div style={{position:'absolute',left:1080,top:300,width:580,height:420,borderRadius:40,border:`3px solid ${C.red}66`,background:'rgba(28,10,12,.55)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:45,fontWeight:950,color:C.red,textAlign:'center'}}>新しい評価軸<br/>？</div></Scene>};
const TinyGapBigMeaning=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene><Headline>{b===45?'小さな差が、巨大な意味を持ち始める':'全員90点なら、89.9点が目立つ'}</Headline>{b===45?['身長 2cm','年収 50万','フォロワー 3000','偏差値 3'].map((t,i)=><Pill key={t} x={220+(i%2)*760} y={320+Math.floor(i/2)*260} text={t} color={[C.cyan,C.amber,C.red,C.violet][i]} delay={i*6} scale={1.18}/>):<><div style={{position:'absolute',left:260,top:390,fontSize:130,fontWeight:950,color:C.cyan}}>90.0</div><div style={{position:'absolute',right:260,top:390,fontSize:130,fontWeight:950,color:C.red}}>89.9</div><Arrow x={760} y={540} w={400} color={C.red}/><Pill x={710} y={720} text="差は0.1、意味は巨大" color={C.red}/></>}</Scene>};
const BottomRank=({beat}:{beat:Beat})=>{const b=bn(beat.id);const vals=[92,91.8,91.6,91.4,91.2,91];return <Scene tone="black"><Headline>{b===47?'「醜い」は顔の形か、順位表の下位か？':'全員が美しくても、最下位は残る'}</Headline>{vals.map((v,i)=><div key={i} style={{position:'absolute',left:300,top:260+i*95,width:1200,height:65,borderRadius:14,background:i===vals.length-1?C.red:C.grey,opacity:i===vals.length-1?1:.35}}><span style={{position:'absolute',left:20,top:10,fontSize:30,fontWeight:950}}>{i+1}位</span><span style={{position:'absolute',right:25,top:10,fontSize:30,fontWeight:950}}>{v}</span></div>)}</Scene>};
const MetricEscape=({beat}:{beat:Beat})=>{const b=bn(beat.id);const labels=b===49?['顔','体型','収入']:['収入','知性','人気','希少性'];return <Scene tone="blue"><Headline>違いを消すたび、新しい違いが見つかる</Headline>{labels.map((t,i)=><React.Fragment key={t}><div style={{position:'absolute',left:220+i*430,top:380+i*70,width:290,height:200,borderRadius:34,border:`3px solid ${[C.pink,C.cyan,C.amber,C.violet][i]}66`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:44,fontWeight:950}}>{t}</div>{i<labels.length-1&&<Arrow x={500+i*430} y={500+i*70} w={170} angle={10} color={C.paper}/>}</React.Fragment>)}</Scene>};
const IndividualityReturn=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="rose"><Headline>{b===51?'最後に価値を持つのは「他と違うこと」かもしれない':'希少性は、いつも少し先へ逃げる'}</Headline>{Array.from({length:8},(_,i)=><Face key={i} x={180+i*205} y={390} size={150} color={i===6?C.amber:C.pink}/>) }<div style={{position:'absolute',left:1385,top:530,width:24,height:24,borderRadius:'50%',background:C.red,boxShadow:`0 0 24px ${C.red}`}}/><Pill x={690} y={760} text={b===51?'完璧さより、記憶に残る個性':'完璧 → 不完全 → 個性'} color={C.amber}/></Scene>};
const EndingQuestion=({beat}:{beat:Beat})=>{const b=bn(beat.id);return <Scene tone="black"><Headline>{b===53?'ルッキズムの正体は「顔」なのか？':'全員を美しくしても、盤面が変わるだけかもしれない'}</Headline><div style={{position:'absolute',left:760,top:300,width:400,height:400,borderRadius:'50%',border:`6px solid ${C.paper}33`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:92,fontWeight:950}}>?</div>{['比較','順位','希少性'].map((t,i)=><Pill key={t} x={420+i*510} y={790} text={t} color={[C.cyan,C.red,C.amber][i]}/>)}</Scene>};
const EndingBlack=()=>{const f=useCurrentFrame();const q=p(f,0,50);return <Scene tone="black"><div style={{position:'absolute',left:220,right:220,top:330,textAlign:'center',fontSize:78,fontWeight:950,lineHeight:1.45,opacity:q,transform:`scale(${.94+.06*q})`}}>問題だったのは、<br/>顔の点数ではなかった。<br/><span style={{color:C.red}}>点数をつけることそのものだった。</span></div></Scene>};

export const RichScene=({beat}:{beat:Beat})=>{switch(beat.visual){
case 'future_city':return <FutureCity beat={beat}/>;case 'beauty_floor':return <BeautyFloor/>;case 'new_axes':return <NewAxes/>;case 'thesis_reveal':return <ThesisReveal/>;case 'two_values':return <TwoValues beat={beat}/>;case 'height_context':return <HeightContext/>;case 'scarcity_dilution':return <ScarcityDilution/>;case 'positional_good':return <PositionalGood beat={beat}/>;case 'selection_machine':return <SelectionMachine/>;case 'micro_features':return <MicroFeatures beat={beat}/>;case 'social_compare':return <SocialCompare/>;case 'moving_average':return <MovingAverage/>;case 'decimal_ranking':return <DecimalRanking beat={beat}/>;case 'dating_grid':return <DatingGrid beat={beat}/>;case 'app_filters':return <AppFilters beat={beat}/>;case 'minimum_standard':return <MinimumStandard beat={beat}/>;case 'floor_ceiling':return <FloorCeiling/>;case 'red_queen':return <RedQueen beat={beat}/>;case 'treadmill':return <Treadmill/>;case 'future_2050':return <Future2050 beat={beat}/>;case 'zoomed_flaws':return <ZoomedFlaws/>;case 'ranking_desire':return <RankingDesire/>;case 'metric_migration':return <MetricMigration/>;case 'credential_parallel':return <CredentialParallel beat={beat}/>;case 'god_upgrade':return <GodUpgrade/>;case 'ranking_reborn':return <RankingReborn/>;case 'imperfection_luxury':return <ImperfectionLuxury beat={beat}/>;case 'status_cycle':return <StatusCycle/>;case 'global_feed':return <GlobalFeed beat={beat}/>;case 'not_necessarily_hell':return <NotNecessarilyHell beat={beat}/>;case 'tiny_gap_big_meaning':return <TinyGapBigMeaning beat={beat}/>;case 'bottom_rank':return <BottomRank beat={beat}/>;case 'metric_escape':return <MetricEscape beat={beat}/>;case 'individuality_return':return <IndividualityReturn beat={beat}/>;case 'ending_question':return <EndingQuestion beat={beat}/>;case 'ending_black':return <EndingBlack/>;default:return <Scene><Headline>{beat.visual}</Headline></Scene>}}
