import React from 'react';
import {interpolate,useCurrentFrame} from 'remotion';
import {OfficeWorkerRig} from '../../shared/asset-library/人物テンプレート/office-worker-rig';
import {OfficeWomanRig} from '../../shared/asset-library/人物テンプレート/office-woman-rig';
import {ParentFatherRig} from '../../shared/asset-library/人物テンプレート/PARENT_FATHER';
import {ParentMotherRig} from '../../shared/asset-library/人物テンプレート/PARENT_MOTHER';
import {V46_CHILD_RIG_BOY} from '../../shared/asset-library/人物テンプレート/V46_CHILD_RIG_BOY';
import {V46_CHILD_RIG_GIRL} from '../../shared/asset-library/人物テンプレート/V46_CHILD_RIG_GIRL';
import {PASSERBY} from '../../shared/asset-library/人物テンプレート/PASSERBY';

export const clamp=(a:number)=>Math.max(0,Math.min(1,a));
export const lerp=(a:number,b:number,t:number)=>a+(b-a)*clamp(t);
export const pulse=(t:number)=>Math.sin(t*Math.PI*2);
export const rise=(t:number,a=.08,b=.4)=>clamp((t-a)/(b-a));
export type CharacterKind='hero'|'peer'|'youngHero'|'youngPeer'|'male'|'female'|'father'|'mother'|'boy'|'girl'|'crowd';
export const Actor=({kind,x,y,scale=.58,motion='idle',pose={},mirror=false,variant=false}:{kind:CharacterKind;x:number;y:number;scale?:number;motion?:'idle'|'walk'|'front'|'run';pose?:Record<string,number>;mirror?:boolean;variant?:boolean})=>{
  const t=useCurrentFrame()/30;
  const breathing={...pose,bodyLean:(pose.bodyLean??0)+Math.sin(t*1.6)*.6};
  switch(kind){
   case 'hero':return <OfficeWorkerRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} showBriefcase={motion==='walk'} mirror={mirror}/>;
   case 'youngHero':return <OfficeWorkerRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} suitColor="#7f948e" pantsColor="#394d5c" shirtColor="#e4ddd1" hairColor="#30363e" showBriefcase={false} mirror={mirror}/>;
   case 'youngPeer':return <OfficeWorkerRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} suitColor="#b39780" pantsColor="#394153" shirtColor="#e9ddd3" hairColor="#51332e" skinColor="#ddb79a" showBriefcase={false} mirror={mirror}/>;
   case 'peer':return <OfficeWorkerRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} suitColor="#674f53" pantsColor="#443940" shirtColor="#fbf0e9" hairColor="#4f322d" skinColor="#ddb79a" showBriefcase={motion==='walk'} mirror={mirror}/>;
   case 'male':return <OfficeWorkerRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} suitColor={variant?"#536b50":"#596779"} pantsColor="#404b56" hairColor={variant?"#675746":"#51453f"} showBriefcase={false} mirror={mirror}/>;
   case 'female':return <OfficeWomanRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} suitColor="#616c72" shirtColor="#e3d9d5" mirror={mirror}/>;
   case 'father':return <ParentFatherRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} hairColor="#4f322d" skinColor="#ddb79a" mirror={mirror}/>;
   case 'mother':return <ParentMotherRig x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'} pose={breathing} topColor={variant?"#596d8c":"#9a766b"} hairColor={variant?"#353f52":"#453340"} mirror={mirror}/>;
   case 'boy':return <V46_CHILD_RIG_BOY x={x} y={y} scale={scale} action={motion==='run'?'run':'front'} pose={breathing} topColor={variant?"#88aa64":"#5a9ec2"} mirror={mirror}/>;
   case 'girl':return <V46_CHILD_RIG_GIRL x={x} y={y} scale={scale} action={motion==='run'?'run':'front'} pose={breathing} mirror={mirror}/>;
   case 'crowd':return <PASSERBY x={x} y={y} scale={scale} action={motion==='walk'?'walk':'idle'}/>;
  }
};
export const Surface=({x,y,w,h,children,bg='rgba(12,17,23,.91)',border='1px solid rgba(255,255,255,.22)',radius=7,opacity=1,rotate=0,style={}}:{x:number;y:number;w:number;h:number;children?:React.ReactNode;bg?:string;border?:string;radius?:number;opacity?:number;rotate?:number;style?:React.CSSProperties})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,background:bg,border,borderRadius:radius,opacity,transform:`rotate(${rotate}deg)`,boxSizing:'border-box',overflow:'hidden',...style}}>{children}</div>;
export const Paper=({x,y,w=172,h=224,progress=.3,rotate=0,kind='document',opacity=1}:{x:number;y:number;w?:number;h?:number;progress?:number;rotate?:number;kind?:'document'|'ledger'|'calendar'|'floorplan'|'schedule';opacity?:number})=><Surface x={x} y={y} w={w} h={h} bg="#ede8d7" border="2px solid #bbb2a1" opacity={opacity} rotate={rotate}>
  {kind==='floorplan'?<svg viewBox="0 0 100 110" style={{width:'100%',height:'100%',padding:9,boxSizing:'border-box'}}><rect x="8" y="10" width="83" height="90" fill="none" stroke="#59646a" strokeWidth="2"/><path d="M8 48H52V10 M52 32H91 M27 48V100 M27 74H91 M52 32V74" stroke="#67777d" strokeWidth="2" fill="none"/><path d="M56 74q10 0 10 10" stroke="#8c999b" fill="none"/></svg>:
  kind==='calendar'?<svg viewBox="0 0 140 140" style={{width:'100%',height:'100%',padding:8,boxSizing:'border-box'}}><rect x="10" y="10" width="120" height="18" rx="3" fill="#b96f68"/>{Array.from({length:28},(_,i)=><rect key={i} x={13+(i%7)*16} y={36+Math.floor(i/7)*22} width="9" height="9" rx="1" fill={i===21?"#a44b48":"#a6aaa5"}/>)}</svg>:
  <><div style={{height:14,background:'#adb8bd',margin:'17px 14px'}}/>{Array.from({length:kind==='ledger'?8:kind==='schedule'?6:5},(_,i)=><div key={i} style={{height:5,margin:'13px 17px',width:`${40+(i%3)*16}%`,background:i<Math.ceil(progress*8)?'#63747b':'#b8b8ac'}}/>)}</>}
 </Surface>;
export const Phone=({x,y,scale=1,screen='dark',tilt=0,glow=true}:{x:number;y:number;scale?:number;screen?:'dark'|'photo'|'notice'|'budget'|'contacts';tilt?:number;glow?:boolean})=><div style={{position:'absolute',left:x,top:y,width:92*scale,height:168*scale,transform:`rotate(${tilt}deg)`,borderRadius:13*scale,border:'5px solid #1d232b',background:'#080f18',boxShadow:glow?'0 0 23px rgba(173,194,219,.27)':'none',boxSizing:'border-box',overflow:'hidden'}}>
  <div style={{position:'absolute',inset:5*scale,borderRadius:7*scale,background:screen==='dark'?'#151c25':screen==='photo'?'linear-gradient(150deg,#ccb9a8,#8a7e77 50%,#d7c1ac)':screen==='budget'?'#d4dfd9':screen==='contacts'?'#e9eced':'#314b64'}}/>
  {screen==='photo'?<><div style={{position:'absolute',width:20*scale,height:20*scale,borderRadius:'50%',background:'#e5bd9f',top:46*scale,left:25*scale}}/><div style={{position:'absolute',width:21*scale,height:20*scale,borderRadius:'50%',background:'#c99387',top:43*scale,left:49*scale}}/><div style={{position:'absolute',height:31*scale,width:47*scale,background:'#6a7265',top:67*scale,left:20*scale}}/><div style={{position:'absolute',height:8*scale,width:20*scale,borderRadius:'50%',background:'#f0e2c1',top:98*scale,left:35*scale}}/></>:screen==='notice'||screen==='contacts'?Array.from({length:3},(_,i)=><div key={i} style={{position:'absolute',left:14*scale,top:(41+i*30)*scale,width:57*scale,height:17*scale,background:'#94b6ca',borderRadius:4*scale,opacity:.85}}/>):screen==='budget'?Array.from({length:5},(_,i)=><div key={i} style={{position:'absolute',left:12*scale,top:(30+i*23)*scale,width:61*scale,height:5*scale,background:i===4?'#4c8c76':'#86989e'}}/>):null}
  <div style={{position:'absolute',bottom:5*scale,left:37*scale,width:12*scale,height:2*scale,background:'#dce4e7',borderRadius:4}}/>
 </div>;
export const Door=({x,y,w=150,h=270,opening=0}:{x:number;y:number;w?:number;h?:number;opening?:number})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,border:'5px solid #62747e',background:'rgba(130,165,176,.16)',boxSizing:'border-box'}}><div style={{position:'absolute',left:w/2-2,top:0,width:3,height:h,background:'#8fa8aa'}}/><div style={{position:'absolute',left:3,top:0,width:(w-10)/2*(1-clamp(opening)),height:h-10,border:'2px solid #bbd0d0',background:'rgba(178,206,215,.22)'}}/><div style={{position:'absolute',right:3,top:0,width:(w-10)/2*(1-clamp(opening)),height:h-10,border:'2px solid #bbd0d0',background:'rgba(178,206,215,.22)'}}/></div>;
export const Cup=({x,y,scale=1,tilt=0}:{x:number;y:number;scale?:number;tilt?:number})=><div style={{position:'absolute',left:x,top:y,width:27*scale,height:31*scale,transform:`rotate(${tilt}deg)`,border:'3px solid #d6e5e8',background:'rgba(122,164,192,.6)',borderRadius:'0 0 7px 7px',boxSizing:'border-box'}}/>;
export const Cake=({x,y,scale=1}:{x:number;y:number;scale?:number})=><div style={{position:'absolute',left:x,top:y,width:132*scale,height:60*scale,borderRadius:'45% 45% 12% 12%',border:'4px solid #bd817f',background:'linear-gradient(#f4e3c6 0 35%,#c69b83 35% 64%,#f3dfc0 64%)',boxShadow:'0 8px 14px #0006'}}>{[.22,.5,.78].map((q,i)=><div key={i} style={{position:'absolute',left:q*132*scale,top:-24*scale,width:5*scale,height:24*scale,background:'#e6c8a5'}}><div style={{position:'absolute',top:-9*scale,left:-2*scale,width:9*scale,height:10*scale,borderRadius:'60% 60% 35% 35%',background:'#e9aa65'}}/></div>)}</div>;
export const Goods=({x,y,scale=1,color='#d5dfdc',progress=1}:{x:number;y:number;scale?:number;color?:string;progress?:number})=><div style={{position:'absolute',left:x,top:y,width:58*scale,height:72*scale,background:color,border:'4px solid #788f9b',transform:`translateX(${(1-clamp(progress))*-65}px)`,boxSizing:'border-box'}}><div style={{position:'absolute',top:15*scale,left:10*scale,width:32*scale,height:5*scale,background:'#779ca8'}}/><div style={{position:'absolute',top:29*scale,left:10*scale,width:22*scale,height:4*scale,background:'#9bacad'}}/></div>;
export const Book=({x,y,scale=1,open=0}:{x:number;y:number;scale?:number;open?:number})=><div style={{position:'absolute',left:x,top:y,width:104*scale,height:70*scale,transform:`rotateY(${-70*clamp(open)}deg)`,background:'linear-gradient(90deg,#d1b99b 0 48%,#9faec0 49% 51%,#e5d9bd 52%)',border:'4px solid #7c6b61',borderRadius:3}}/>;
export const Table=({x=450,y=690,w=900,h=130}:{x?:number;y?:number;w?:number;h?:number})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,borderRadius:'10px 10px 3px 3px',background:'linear-gradient(#8c7168,#513d38)',border:'4px solid #3c302f',boxSizing:'border-box',boxShadow:'0 18px 22px #0008'}}/>;
