import React from 'react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';

export type Beat={id:string;visual:string;narration:string;speech?:string};
const font='"Noto Sans CJK JP",sans-serif';
const C={paper:'#f2eee5',muted:'#9aa2aa',ink:'#05070a',blue:'#6e9fbe',cyan:'#75c5c8',amber:'#d4a65c',red:'#b85f59',green:'#80a47f',violet:'#9385ba',grey:'#3a4148'};
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const bn=(id:string)=>Number(id.replace(/\D/g,''))||0;
const ap=(f:number,a=0,b=24)=>interpolate(f,[a,b],[0,1],clamp);

const Dust=()=>{const f=useCurrentFrame();return <>{Array.from({length:38},(_,i)=><div key={i} style={{position:'absolute',left:(i*181+Math.sin((f+i*19)/72)*40)%1920,top:(i*119+f*.08)%1080,width:2+(i%3),height:2+(i%3),borderRadius:20,background:C.paper,opacity:.035+(i%5)*.012}}/>)}</>};

const Scene=({children,tone='night'}:{children:React.ReactNode;tone?:'night'|'blue'|'warm'|'black'|'paper'})=>{
  const f=useCurrentFrame();
  const bg=tone==='blue'?'linear-gradient(145deg,#06131d,#102936 56%,#020406)':tone==='warm'?'linear-gradient(145deg,#170e0a,#342219 56%,#030303)':tone==='paper'?'linear-gradient(145deg,#181611,#2c271e 55%,#060606)':tone==='black'?'#020304':'linear-gradient(145deg,#05070a,#12181d 57%,#030405)';
  return <AbsoluteFill style={{background:bg,color:C.paper,overflow:'hidden',fontFamily:font}}>
    <AbsoluteFill style={{transform:`scale(${1.008+Math.sin(f/170)*.006})`}}>{children}</AbsoluteFill>
    <Dust/>
    <AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,transparent 28%,rgba(0,0,0,.26) 72%,rgba(0,0,0,.82) 100%)'}}/>
  </AbsoluteFill>;
};
const Headline=({children,sub}:{children:React.ReactNode;sub?:string})=><div style={{position:'absolute',left:105,top:70,right:110,fontWeight:950,fontSize:50,letterSpacing:.8,textShadow:'0 5px 28px rgba(0,0,0,.72)'}}>{children}{sub&&<div style={{fontSize:22,color:C.muted,marginTop:10,fontWeight:650}}>{sub}</div>}</div>;
const Pill=({x,y,text,color=C.cyan,delay=0}:{x:number;y:number;text:string;color?:string;delay?:number})=>{const f=useCurrentFrame();const p=ap(f,delay,delay+22);return <div style={{position:'absolute',left:x,top:y,padding:'13px 22px',borderRadius:999,border:`2px solid ${color}66`,background:'rgba(4,8,12,.78)',fontWeight:900,fontSize:29,color,opacity:p,transform:`translateY(${(1-p)*18}px) scale(${.94+.06*p})`}}>{text}</div>};
const Person=({x,y,scale=1,color=C.blue,ghost=false}:{x:number;y:number;scale?:number;color?:string;ghost?:boolean})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,transform:`translateY(${Math.sin((f+x)/48)*5}px) scale(${scale})`,transformOrigin:'50% 100%',opacity:ghost?.45:1,filter:ghost?'blur(.4px) drop-shadow(0 0 25px rgba(117,197,200,.35))':'none'}}>
  <div style={{width:94,height:94,borderRadius:'50%',background:`radial-gradient(circle at 40% 30%,${color},#12161a 75%)`,border:`5px solid ${color}`}}/>
  <div style={{width:142,height:210,borderRadius:'70px 70px 24px 24px',background:`linear-gradient(180deg,${color}aa,#101419)`,marginLeft:-24,marginTop:12,border:`3px solid ${color}77`}}/>
</div>};
const Paper=({x,y,text,rotate=0,color=C.paper,w=330,h=180}:{x:number;y:number;text:string;rotate?:number;color?:string;w?:number;h?:number})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,width:w,height:h,background:'#e8e2d4',color:'#11161a',borderRadius:10,boxShadow:'0 18px 50px rgba(0,0,0,.38)',transform:`rotate(${rotate+Math.sin((f+x)/80)*.7}deg)`,padding:'28px 32px',fontSize:31,fontWeight:900,borderTop:`10px solid ${color}`,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',whiteSpace:'pre-line'}}>{text}</div>};
const Arrow=({x,y,w,angle=0,color=C.amber}:{x:number;y:number;w:number;angle?:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:7,background:color,transform:`rotate(${angle}deg)`,transformOrigin:'0 50%',boxShadow:`0 0 18px ${color}55`}}><div style={{position:'absolute',right:-2,top:-9,width:0,height:0,borderTop:'13px solid transparent',borderBottom:'13px solid transparent',borderLeft:`22px solid ${color}`}}/></div>;

const IntroBarQuestion=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);return <Scene tone="warm"><Headline>{p===1?'32歳。社会人10年目。':'たった一言で、18歳に戻る'}</Headline><div style={{position:'absolute',left:250,top:320,width:1420,height:430,borderRadius:80,background:'linear-gradient(180deg,rgba(82,49,32,.62),rgba(20,13,10,.86))',border:'2px solid rgba(212,166,92,.25)',boxShadow:'0 30px 90px rgba(0,0,0,.42)'}}><div style={{position:'absolute',left:0,right:0,bottom:0,height:80,background:'rgba(91,55,35,.65)'}}/><Person x={500} y={400} scale={1.15} color={C.blue}/><Person x={1250} y={400} scale={1.15} color={C.amber}/><div style={{position:'absolute',left:780,top:145,padding:'28px 42px',borderRadius:38,background:'#eee8db',color:'#12171a',fontSize:42,fontWeight:950,transform:`scale(${.95+.05*ap(f,8,28)})`}}>大学どこだったんですか？</div></div><Pill x={720} y={800} text={p===1?'現在：32歳':'脳内：18歳へ'} color={p===1?C.green:C.red}/></Scene>};

const MemoryDefense=()=>{const f=useCurrentFrame();return <Scene><Headline>頼まれていない弁明が始まる</Headline><Person x={270} y={350} scale={1.25} color={C.blue}/>{['高校では成績よかった','第一志望は別だった','センターで少し失敗'].map((t,i)=><div key={t} style={{position:'absolute',left:610+i*70,top:280+i*150,width:720,padding:'26px 34px',borderRadius:28,background:'rgba(9,14,19,.86)',border:`2px solid ${[C.cyan,C.amber,C.red][i]}66`,fontSize:38,fontWeight:900,opacity:ap(f,i*9,i*9+25),transform:`translateX(${(1-ap(f,i*9,i*9+25))*90}px)`}}>{t}</div>)}<Pill x={810} y={800} text="誰も聞いていない" color={C.red} delay={20}/></Scene>};

const TimeGap=()=>{const f=useCurrentFrame();const t=interpolate(f,[0,80],[0,1],clamp);return <Scene tone="black"><Headline>18歳の試験が、32歳の自己評価に残る</Headline><div style={{position:'absolute',left:250,right:250,top:520,height:8,background:'rgba(255,255,255,.15)'}}><div style={{width:`${t*100}%`,height:'100%',background:C.cyan,boxShadow:`0 0 30px ${C.cyan}`}}/></div><Pill x={220} y={430} text="18歳：受験" color={C.red}/><Pill x={1480} y={430} text="32歳：現在" color={C.green}/><div style={{position:'absolute',left:interpolate(t,[0,1],[300,1540]),top:505,width:38,height:38,borderRadius:'50%',background:C.paper,boxShadow:'0 0 40px rgba(242,238,229,.8)'}}/><div style={{position:'absolute',left:780,top:680,fontSize:64,fontWeight:950}}>10年経っても、まだ採点中</div></Scene>};

const RankEscalator=()=>{const f=useCurrentFrame();const labels=['日東駒専','MARCH','早慶','東大','医学部 / 海外トップ大'];return <Scene tone="blue"><Headline>上へ行けば、さらに上が見える</Headline>{labels.map((t,i)=>{const p=ap(f,i*6,i*6+24);return <div key={t} style={{position:'absolute',left:250+i*280,top:760-i*105,width:260,height:85,borderRadius:18,background:'rgba(8,18,26,.86)',border:`2px solid ${[C.grey,C.blue,C.cyan,C.amber,C.red][i]}88`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:29,fontWeight:950,opacity:p,transform:`translateY(${(1-p)*35}px)`}}>{t}</div>})}<Arrow x={360} y={825} w={1120} angle={-22} color={C.amber}/></Scene>};

const ThesisReveal=()=>{const f=useCurrentFrame();const p=ap(f,4,34);return <Scene tone="black"><div style={{position:'absolute',left:170,right:170,top:220,textAlign:'center',fontSize:34,color:C.muted,fontWeight:700}}>学歴コンプの正体</div><div style={{position:'absolute',left:190,right:190,top:340,textAlign:'center',fontSize:72,fontWeight:950,lineHeight:1.35,opacity:p,transform:`scale(${.92+.08*p})`}}>社会の序列 ×<br/><span style={{color:C.cyan}}>「本当ならもっと上だった自分」</span></div><div style={{position:'absolute',left:650,top:760,width:620,height:3,background:`linear-gradient(90deg,transparent,${C.red},transparent)`}}/></Scene>};

const CredentialZip=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const tags=p===7?['記憶力','論理力','創造力','忍耐力','文章力','対人能力']:['会社名','役職','年収','資格','大学名'];return <Scene><Headline>{p===7?'複雑な人間を、社会は圧縮する':'数文字で人間を推測する'}</Headline>{tags.map((t,i)=>{const angle=(i/tags.length)*Math.PI*2;const sx=960+Math.cos(angle)*520,sy=540+Math.sin(angle)*280;const tx=960,ty=550;const m=ap(f,10+i*4,52+i*4);return <Pill key={t} x={interpolate(m,[0,1],[sx,tx-70+i*28])} y={interpolate(m,[0,1],[sy,ty-20+(i%2)*55])} text={t} color={[C.blue,C.cyan,C.amber,C.red,C.green,C.violet][i%6]}/>})}<div style={{position:'absolute',left:780,top:390,width:360,height:300,borderRadius:44,border:`4px solid ${C.paper}44`,background:'rgba(0,0,0,.52)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:92,fontWeight:950}}>ZIP</div></Scene>};

const SignalNetwork=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const pulse=.65+.35*Math.sin(f/18);return <Scene tone="blue"><Headline>{p===9?'大学名は「能力の略号」になる':'見えない能力を、見える記号で推測する'}</Headline><Person x={250} y={380} scale={1.25} color={C.paper}/><div style={{position:'absolute',left:760,top:370,width:380,height:260,borderRadius:30,border:`4px solid ${C.cyan}`,background:'rgba(8,18,25,.82)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:52,fontWeight:950,boxShadow:`0 0 ${30*pulse}px ${C.cyan}55`}}>大学名</div>{['企業','社会','他人','自分自身'].map((t,i)=><React.Fragment key={t}><Arrow x={1160} y={430+i*75} w={350} angle={(i-1.5)*8} color={[C.amber,C.blue,C.green,C.red][i]}/><Pill x={1510} y={350+i*135} text={t} color={[C.amber,C.blue,C.green,C.red][i]} delay={i*5}/></React.Fragment>)}</Scene>};

const StatusBadge=()=>{const f=useCurrentFrame();const p=ap(f,5,40);return <Scene tone="black"><Headline>巨大な問いに、雑な数字で答える</Headline><Person x={380} y={350} scale={1.4} color={C.blue}/><div style={{position:'absolute',left:850,top:270,fontSize:42,fontWeight:800,color:C.muted}}>自分はどの程度の人間か？</div><div style={{position:'absolute',left:870,top:430,width:650,height:250,borderRadius:36,background:'linear-gradient(145deg,#e9e2d3,#bfb6a5)',color:'#11161a',transform:`rotate(${interpolate(p,[0,1],[8,-2])}deg) scale(${.82+.18*p})`,boxShadow:'0 30px 80px rgba(0,0,0,.45)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:74,fontWeight:950}}>偏差値 / 大学名</div><Pill x={980} y={760} text="自己評価のショートカット" color={C.red}/></Scene>};

const PositionalLadder=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const all=Array.from({length:12},(_,i)=>i);return <Scene><Headline>{p===12?'全員が東大卒なら、東大卒は希少ではない':'学歴は「位置」の価値も持つ'}</Headline><div style={{position:'absolute',left:300,top:280,width:1320,height:500,display:'flex',alignItems:'flex-end',gap:18}}>{all.map((_,i)=>{const h=120+i*28;const hi=p===12?C.cyan:(i>8?C.amber:C.grey);return <div key={i} style={{width:86,height:h,borderRadius:'18px 18px 4px 4px',background:hi,opacity:.35+.65*ap(f,i*3,i*3+24),boxShadow:i>8?`0 0 25px ${hi}55`:'none'}}/>})}</div><Pill x={700} y={820} text={p===12?'希少性が消える':'相対的位置そのものが価値'} color={p===12?C.cyan:C.amber}/></Scene>};

const MovingGoalpost=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const x=interpolate(f,[0,120],[500,1450],clamp);return <Scene tone="blue"><Headline>{p===14?'上へ行くほど、ゴールが逃げる':'学歴コンプには理論上ゴールがない'}</Headline><Person x={350} y={500} scale={1.05} color={C.paper}/><div style={{position:'absolute',left:x,top:330,width:34,height:450,background:C.amber,boxShadow:`0 0 25px ${C.amber}66`}}><div style={{position:'absolute',left:0,top:0,width:240,height:110,background:C.red,clipPath:'polygon(0 0,100% 50%,0 100%)'}}/></div><Arrow x={560} y={650} w={760} color={C.cyan}/><Pill x={760} y={790} text="順位表そのものが拡張される" color={C.red}/></Scene>};

const SocialCompareOrbit=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>気になるのは「自分もそこにいたかもしれない人」</Headline><Person x={850} y={430} scale={1.15} color={C.blue}/>{['高校の同級生','模試A判定の友人','あと少し上だった人'].map((t,i)=>{const a=f/70+i*2.09;const x=900+Math.cos(a)*520,y=500+Math.sin(a)*260;return <Pill key={t} x={x} y={y} text={t} color={[C.amber,C.cyan,C.red][i]}/>})}<div style={{position:'absolute',left:745,top:810,fontSize:32,color:C.muted,fontWeight:800}}>比較は「遠い天才」より「近い別人生」に刺さる</div></Scene>};

const NearMissGate=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const gap=interpolate(f,[0,55],[260,28],clamp);return <Scene tone="paper"><Headline>{p===17?'大敗より「惜敗」が残ることがある':'あと3点。あと一問。あと一日。'}</Headline><div style={{position:'absolute',left:300,top:300,width:500,height:500,border:'8px solid rgba(242,238,229,.35)',borderRadius:40}}><div style={{position:'absolute',right:gap,top:0,bottom:0,width:12,background:C.red}}><div style={{position:'absolute',right:-95,top:190,fontSize:62,fontWeight:950,color:C.red,whiteSpace:'nowrap'}}>合格</div></div><div style={{position:'absolute',left:80,top:210,width:68,height:68,borderRadius:'50%',background:C.blue,boxShadow:`0 0 25px ${C.blue}66`}}/></div><div style={{position:'absolute',left:1040,top:390,fontSize:110,fontWeight:950,color:C.amber}}>{p===17?'3点差':'あと少し'}</div><Pill x={1120} y={650} text="近い失敗ほど「別世界」が作りやすい" color={C.cyan}/></Scene>};

const CounterfactualBranch=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);return <Scene tone="blue"><Headline>{p===19?'反実仮想：起きなかった世界を作る':'同じ失敗でも、近いほど痛い'}</Headline><div style={{position:'absolute',left:300,top:520,width:380,height:10,background:C.paper}}/><Person x={250} y={360} scale={.9} color={C.paper}/>{[-1,1].map((d,i)=><React.Fragment key={d}><Arrow x={680} y={525} w={540} angle={d*22} color={i?C.cyan:C.red}/><Pill x={1200} y={i?650:300} text={i?(p===19?'もし、あの問題を取っていたら':'2分差で乗れた世界'):(p===19?'現実に起きた人生':'現実：乗れなかった')} color={i?C.cyan:C.red} delay={8+i*7}/></React.Fragment>)}<div style={{position:'absolute',left:760,top:820,fontSize:34,fontWeight:850,color:C.muted,opacity:.8+.2*Math.sin(f/20)}}>脳は分岐点を何度でも再生する</div></Scene>};

const GhostSelf=({beat}:{beat:Beat})=>{const p=bn(beat.id);return <Scene tone="black"><Headline>{p===21?'第一志望に受かっていた「もう一人の自分」':'存在しない人生には、失敗の記録がない'}</Headline><Person x={430} y={410} scale={1.35} color={C.grey}/><Person x={1260} y={410} scale={1.35} color={C.cyan} ghost/><div style={{position:'absolute',left:300,top:770,fontSize:32,fontWeight:850,color:C.muted}}>現実の自分</div><div style={{position:'absolute',left:1170,top:770,fontSize:32,fontWeight:850,color:C.cyan}}>あり得たかもしれない自分</div><Arrow x={700} y={520} w={480} color={C.red}/><Pill x={770} y={650} text={p===21?'比較開始':'失敗ログ：0件'} color={p===21?C.red:C.green}/></Scene>};

const EditedLife=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const real=['失敗','黒歴史','月曜','税金'];return <Scene><Headline>{p===23?'架空の人生は、都合よく編集できる':'現実 vs 編集済みの架空人生'}</Headline><div style={{position:'absolute',left:230,top:300,width:610,height:480,borderRadius:36,border:`3px solid ${C.red}66`,background:'rgba(25,11,11,.55)'}}>{real.map((t,i)=><Pill key={t} x={300+(i%2)*250} y={370+Math.floor(i/2)*170} text={t} color={C.red} delay={i*6}/>)}</div><div style={{position:'absolute',left:1080,top:300,width:610,height:480,borderRadius:36,border:`3px solid ${C.cyan}66`,background:'rgba(8,24,27,.55)'}}><div style={{position:'absolute',left:150,top:120,fontSize:70,fontWeight:950,color:C.cyan}}>理想化</div><div style={{position:'absolute',left:125,top:250,fontSize:40,fontWeight:900}}>都合の悪い部分を削除</div><div style={{position:'absolute',left:100,top:340,width:420,height:8,background:C.cyan,transform:`scaleX(${ap(f,0,70)})`,transformOrigin:'0 50%'}}/></div><Pill x={780} y={820} text={p===23?'想像は編集可能':'当然、現実が不利'} color={C.amber}/></Scene>};

const PossibleSelves=()=>{const f=useCurrentFrame();const labels=[['現在の自分',C.paper],['なりたい自分',C.cyan],['なれたかもしれない自分',C.amber],['なりたくない自分',C.red]] as const;return <Scene tone="blue"><Headline>Possible Selves — 頭の中には複数の「自分」がいる</Headline>{labels.map(([t,c],i)=>{const x=300+i*410;return <div key={t} style={{position:'absolute',left:x,top:340,opacity:ap(f,i*7,i*7+25)}}><Person x={0} y={0} scale={1} color={c} ghost={i>0}/><div style={{position:'absolute',left:-70,top:350,width:280,textAlign:'center',fontSize:28,fontWeight:900,color:c}}>{t}</div></div>})}</Scene>};

const DiscardedFuture=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const paths=['医者','研究者','起業家','東京の大学','別の会社'];return <Scene tone="black"><Headline>{p===26?'18歳は「何者にでもなれる」が最も大きい時期':'合格発表で、一つの未来が消える'}</Headline><Person x={300} y={430} scale={1.05} color={C.paper}/>{paths.map((t,i)=><React.Fragment key={t}><Arrow x={500} y={540} w={650+i*120} angle={(i-2)*13} color={i===3?C.red:[C.blue,C.cyan,C.amber,C.green,C.violet][i]}/><Pill x={1120+(i%2)*260} y={250+i*120} text={t} color={i===3?C.red:[C.blue,C.cyan,C.amber,C.green,C.violet][i]} delay={i*5}/></React.Fragment>)}{p===27&&<div style={{position:'absolute',left:1040,top:610,width:560,height:12,background:C.red,transform:`rotate(-11deg) scaleX(${ap(f,10,45)})`,transformOrigin:'0 50%'}}/>}</Scene>};

const ArchiveReopen=()=>{const f=useCurrentFrame();const y=interpolate(ap(f,10,50),[0,1],[820,370]);return <Scene><Headline>人生がうまくいかないたび、古いファイルが開く</Headline><div style={{position:'absolute',left:250,top:300,width:500,height:480,borderRadius:30,background:'rgba(8,12,16,.7)',border:'2px solid rgba(255,255,255,.13)'}}>{['仕事がつまらない','昇進に負けた','給料が上がらない'].map((t,i)=><Pill key={t} x={300} y={380+i*125} text={t} color={[C.grey,C.red,C.amber][i]} delay={i*7}/>)}</div><div style={{position:'absolute',left:1030,top:y,width:560,height:330,borderRadius:22,background:'#d9d1c1',color:'#11161a',padding:40,boxShadow:'0 30px 80px rgba(0,0,0,.5)',fontSize:40,fontWeight:950}}>削除済み？<div style={{marginTop:70,color:'#6d5140'}}>「第一志望に行っていたら」</div></div></Scene>};

const MeritocracyMachine=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const x=interpolate(f%140,[0,139],[200,1500]);return <Scene tone="blue"><Headline>{p===29?'能力主義：敗北を「自分の価値」に変える装置':'公平な競争には、副作用がある'}</Headline><div style={{position:'absolute',left:180,top:650,width:1550,height:22,background:'#272e33'}}>{Array.from({length:16},(_,i)=><div key={i} style={{position:'absolute',left:i*100,top:-14,width:46,height:46,borderRadius:'50%',background:'#48515a',transform:`rotate(${f*3}deg)`}}/>)}</div><Paper x={x} y={470} text="受験結果" color={C.amber} w={280} h={150}/><div style={{position:'absolute',left:760,top:280,width:410,height:240,borderRadius:30,border:`4px solid ${C.cyan}`,background:'rgba(5,15,22,.85)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:54,fontWeight:950}}>能力主義</div><Arrow x={1170} y={400} w={370} color={C.red}/><Pill x={1430} y={330} text={p===29?'自己価値':'自己責任'} color={C.red}/></Scene>};

const FairnessCourt=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const scale=1+.06*Math.sin(f/14);return <Scene tone="paper"><Headline>{p===31?'競争が不公平なら、外部要因を語れる':'競争が公平になるほど、敗北は個人化される'}</Headline><div style={{position:'absolute',left:820,top:270,width:280,height:430,borderRadius:'50% 50% 20px 20px',background:'#261b14',border:`4px solid ${C.amber}77`}}><div style={{position:'absolute',left:70,top:70,fontSize:52,fontWeight:950,color:C.amber}}>判決</div><div style={{position:'absolute',left:80,top:180,fontSize:86,fontWeight:950,transform:`scale(${scale})`,color:p===31?C.grey:C.red}}>{p===31?'環境':'自分'}</div></div><div style={{position:'absolute',left:310,top:430,width:330,height:22,background:C.paper,transform:'rotate(-8deg)'}}/><div style={{position:'absolute',left:1270,top:430,width:330,height:22,background:C.paper,transform:'rotate(8deg)'}}/><Pill x={250} y={710} text="生まれ / コネ / 制度" color={C.grey}/><Pill x={1280} y={710} text="能力 / 努力" color={C.red}/></Scene>};

const PersonalizedDefeat=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);return <Scene tone="black"><Headline>{p===33?'試験結果が「自己判決」に変換される':'十年残るのは、大学名ではなく判決'}</Headline>{['合格','不合格','偏差値','判定','順位'].map((t,i)=><Paper key={t} x={180+i*320} y={300+(i%2)*80} text={t} rotate={(i-2)*2} color={[C.green,C.red,C.amber,C.blue,C.violet][i]} w={260} h={150}/>)}<div style={{position:'absolute',left:680,top:650,width:560,height:190,borderRadius:30,background:'rgba(97,24,22,.45)',border:`4px solid ${C.red}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:50,fontWeight:950,transform:`scale(${.96+.04*ap(f,20,48)})`}}>「自分はこの程度」</div></Scene>};

const StatusFossil=()=>{const f=useCurrentFrame();const rot=Math.sin(f/80)*2;return <Scene tone="paper"><Headline>18歳の序列が「化石」になる</Headline><div style={{position:'absolute',left:520,top:260,width:900,height:600,borderRadius:'48% 44% 52% 46%',background:'radial-gradient(circle at 45% 40%,#6f6556,#28231d 70%)',boxShadow:'inset 0 0 90px rgba(0,0,0,.55),0 30px 80px rgba(0,0,0,.4)',transform:`rotate(${rot}deg)`}}><div style={{position:'absolute',left:230,top:180,fontSize:58,fontWeight:950,color:'#cfc5b3',transform:'rotate(-8deg)'}}>○○大学卒</div><div style={{position:'absolute',left:300,top:330,fontSize:34,color:'#9d927f'}}>18歳 → 32歳 → 50歳</div></div></Scene>};

const ProfileStamp=()=>{const f=useCurrentFrame();const p=ap(f,8,38);return <Scene><Headline>過去の出来事が、現在形のプロフィールになる</Headline><div style={{position:'absolute',left:330,top:260,width:1260,height:560,borderRadius:38,background:'rgba(242,238,229,.92)',color:'#101419',padding:55}}><div style={{fontSize:48,fontWeight:950}}>PROFILE</div><div style={{marginTop:90,fontSize:36,fontWeight:800}}>職歴：現在の会社</div><div style={{marginTop:34,fontSize:36,fontWeight:800}}>役職：現在の役職</div><div style={{marginTop:34,fontSize:36,fontWeight:800}}>学歴：○○大学卒</div><div style={{position:'absolute',right:90,top:190,border:`10px solid ${C.red}`,color:C.red,padding:'28px 36px',fontSize:48,fontWeight:950,transform:`rotate(-12deg) scale(${.65+.35*p})`,opacity:p}}>10年前の結果</div></div></Scene>};

const AntiAcademicParadox=()=>{const f=useCurrentFrame();return <Scene tone="black"><Headline>克服しようとするほど、学歴を保存する</Headline><Person x={270} y={420} scale={1.1} color={C.paper}/><div style={{position:'absolute',left:760,top:270,width:520,height:520,borderRadius:'50%',border:`10px solid ${C.red}`,boxShadow:`0 0 ${50+20*Math.sin(f/20)}px ${C.red}55`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:58,fontWeight:950,color:C.red,textAlign:'center'}}>東大卒に<br/>勝つ</div><Arrow x={560} y={540} w={190} color={C.cyan}/><Arrow x={1280} y={540} w={300} angle={180} color={C.red}/><Pill x={1250} y={740} text="比較対象として東大を保存" color={C.red}/></Scene>};

const ScoreboardLoop=({beat}:{beat:Beat})=>{const p=bn(beat.id);return <Scene tone="blue"><Headline>{p===38?'勝っても、物差しからは降りていない':'「関係ない」を証明するため、関係を続ける'}</Headline><div style={{position:'absolute',left:280,top:280,width:1360,height:470,borderRadius:44,background:'rgba(2,8,13,.78)',border:'3px solid rgba(255,255,255,.13)',padding:50}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:36,fontSize:46,fontWeight:950}}><div>現在の自分</div><div style={{color:C.red}}>高学歴の他人</div><div style={{fontSize:90,color:C.green}}>{p===38?'年収 2000万':'成功例'}</div><div style={{fontSize:90,color:C.amber}}>{p===38?'東大卒':'失敗例を検索'}</div></div><div style={{position:'absolute',left:500,right:500,bottom:60,height:6,background:C.red}}/></div><Pill x={670} y={820} text="比較している限り、ゲームは続く" color={C.red}/></Scene>};

const SelfDiscrepancy=()=>{const f=useCurrentFrame();const d=interpolate(f,[0,80],[120,600],clamp);return <Scene><Headline>自己不一致：現実の自分と「本来の自分」</Headline><Person x={500} y={410} scale={1.25} color={C.grey}/><Person x={500+d} y={410} scale={1.25} color={C.cyan} ghost/><div style={{position:'absolute',left:380,top:770,fontSize:32,fontWeight:900}}>現実の自分</div><div style={{position:'absolute',left:1030,top:770,fontSize:32,fontWeight:900,color:C.cyan}}>東大に受かっていた自分</div><Arrow x={720} y={560} w={d-100} color={C.red}/><Pill x={800} y={300} text="距離が心理的負担になる" color={C.red}/></Scene>};

const UnreachableSelf=()=>{const f=useCurrentFrame();const wall=interpolate(f,[10,55],[0,1],clamp);return <Scene tone="black"><Headline>この相手には、現在からはなれない</Headline><Person x={330} y={430} scale={1.2} color={C.paper}/><Person x={1360} y={430} scale={1.2} color={C.cyan} ghost/><div style={{position:'absolute',left:900,top:180,width:18,height:720,background:C.red,transform:`scaleY(${wall})`,transformOrigin:'50% 100%',boxShadow:`0 0 30px ${C.red}77`}}/><Pill x={730} y={240} text="時間" color={C.red}/><div style={{position:'absolute',left:645,top:800,fontSize:35,fontWeight:900,color:C.muted}}>年収は抜けても、過去の合格歴は作れない</div></Scene>};

const TimeDistance=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);const blur=Math.min(8,interpolate(f,[0,80],[0,8],clamp));return <Scene tone="blue"><Headline>{p===42?'30代になると「もしも」は別世界になる':'遠ざかるほど、反実仮想は美しくなる'}</Headline><div style={{position:'absolute',left:230,top:330,width:1450,height:12,background:'rgba(255,255,255,.15)'}}><div style={{position:'absolute',left:0,top:-15,width:42,height:42,borderRadius:'50%',background:C.red}}/><div style={{position:'absolute',right:0,top:-15,width:42,height:42,borderRadius:'50%',background:C.green}}/></div><Pill x={190} y={220} text="18歳" color={C.red}/><Pill x={1500} y={220} text="32歳" color={C.green}/><div style={{position:'absolute',left:300,top:560,fontSize:62,fontWeight:950,color:C.cyan,filter:p===43?`blur(${blur}px)`:'none',opacity:p===43?.95:1}}>「あの大学に行っていた人生」</div><Arrow x={420} y={700} w={980} color={C.amber}/><Pill x={760} y={790} text={p===43?'検証不能な仮説は、負けない':'実現可能な未来 → 完全な別世界'} color={C.amber}/></Scene>};

const PastRescue=({beat}:{beat:Beat})=>{const p=bn(beat.id);return <Scene tone="paper"><Headline>{p===44?'本当に欲しいのは「卒業証書」なのか？':'現在の成功では、18歳を書き換えられない'}</Headline><Person x={330} y={430} scale={1.2} color={C.blue}/><Person x={1320} y={430} scale={1.2} color={C.red}/><div style={{position:'absolute',left:690,top:360,width:540,height:280,borderRadius:30,background:'rgba(242,238,229,.92)',color:'#11161a',padding:35,textAlign:'center',fontSize:42,fontWeight:950}}>「あのときの自分は<br/>負けた人間ではなかった」</div><Arrow x={610} y={520} w={90} color={C.cyan}/><Arrow x={1230} y={520} w={90} angle={180} color={C.red}/><Pill x={740} y={730} text="過去の自己像を救済する" color={C.amber}/></Scene>};

const RankInternalization=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);return <Scene tone="black"><Headline>{p===46?'「本当の価値は、あの結果より高かったはず」':'高学歴でも、成功しても、時間が経っても起こる'}</Headline><Person x={780} y={390} scale={1.3} color={C.paper}/>{['偏差値','大学名','他人の順位','あり得た自分'].map((t,i)=>{const a=f/85+i*Math.PI/2;return <Pill key={t} x={900+Math.cos(a)*520} y={500+Math.sin(a)*270} text={t} color={[C.red,C.amber,C.cyan,C.violet][i]}/>})}<div style={{position:'absolute',left:730,top:800,fontSize:34,fontWeight:900,color:C.muted}}>外の順位表が、内側の自己評価になる</div></Scene>};

const ExamHallEmpty=({beat}:{beat:Beat})=>{const p=bn(beat.id);return <Scene tone="paper"><Headline>{p===48?'本来、起きたことはそれだけだった':'出来事に、巨大な意味を載せた'}</Headline>{Array.from({length:20},(_,i)=><div key={i} style={{position:'absolute',left:200+(i%5)*330,top:260+Math.floor(i/5)*145,width:250,height:90,border:'2px solid rgba(242,238,229,.18)',borderRadius:8,background:'rgba(20,18,14,.42)'}}/>)}<Paper x={790} y={410} text={p===48?'一つの試験\n一つの結果':'「自分はこのレベル」'} color={p===48?C.paper:C.red} w={360} h={220}/><Pill x={700} y={830} text={p===48?'試験会場はもう空だ':'意味だけが残る'} color={p===48?C.muted:C.red}/></Scene>};

const EndingMirror=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=bn(beat.id);return <Scene tone="black"><Headline>{p===50?'試験は終わった。それでも採点は続いている':'18歳の順位を、現在まで使い続けている'}</Headline><div style={{position:'absolute',left:600,top:220,width:720,height:650,borderRadius:'50% 50% 42% 42%',border:'8px solid rgba(242,238,229,.24)',background:'linear-gradient(145deg,rgba(117,197,200,.08),rgba(255,255,255,.02))',boxShadow:'inset 0 0 100px rgba(117,197,200,.08)'}}><Person x={285} y={215} scale={1.2} color={C.paper}/><div style={{position:'absolute',left:160,top:70,fontSize:110,fontWeight:950,color:C.red,opacity:.18+.15*Math.sin(f/24)}}>18</div></div><Pill x={710} y={900} text={p===50?'答案はない。採点者だけが残る。':'更新されない自己ランキング'} color={C.red}/></Scene>};

const EndingGhost=({beat}:{beat:Beat})=>{const p=bn(beat.id);return <Scene tone="blue"><Headline>{p===52?'頭のどこかで、18歳の自分がまだ待っている':'存在しない人間に嫉妬できる'}</Headline><Person x={410} y={420} scale={1.3} color={C.paper}/><Person x={1300} y={420} scale={1.3} color={C.cyan} ghost/><div style={{position:'absolute',left:820,top:470,fontSize:90,fontWeight:950,color:C.muted}}>VS</div><Pill x={280} y={800} text="今ここにいる自分" color={C.paper}/><Pill x={1240} y={800} text="存在しなかった自分" color={C.cyan}/></Scene>};

const EndingBlack=()=>{const f=useCurrentFrame();const p=ap(f,0,55);return <Scene tone="black"><div style={{position:'absolute',left:240,right:240,top:360,textAlign:'center',fontSize:70,fontWeight:950,lineHeight:1.45,opacity:p,transform:`scale(${.94+.06*p})`}}>これほど贅沢で、<br/><span style={{color:C.red}}>これほど残酷な知性の使い方もない。</span></div></Scene>};

export const RichScene=({beat}:{beat:Beat})=>{
  switch(beat.visual){
    case 'intro_bar_question': return <IntroBarQuestion beat={beat}/>;
    case 'memory_defense': return <MemoryDefense/>;
    case 'time_gap': return <TimeGap/>;
    case 'rank_escalator': return <RankEscalator/>;
    case 'thesis_reveal': return <ThesisReveal/>;
    case 'credential_zip': return <CredentialZip beat={beat}/>;
    case 'signal_network': return <SignalNetwork beat={beat}/>;
    case 'status_badge': return <StatusBadge/>;
    case 'positional_ladder': return <PositionalLadder beat={beat}/>;
    case 'moving_goalpost': return <MovingGoalpost beat={beat}/>;
    case 'social_compare_orbit': return <SocialCompareOrbit/>;
    case 'near_miss_gate': return <NearMissGate beat={beat}/>;
    case 'counterfactual_branch': return <CounterfactualBranch beat={beat}/>;
    case 'ghost_self': return <GhostSelf beat={beat}/>;
    case 'edited_life': return <EditedLife beat={beat}/>;
    case 'possible_selves': return <PossibleSelves/>;
    case 'discarded_future': return <DiscardedFuture beat={beat}/>;
    case 'archive_reopen': return <ArchiveReopen/>;
    case 'meritocracy_machine': return <MeritocracyMachine beat={beat}/>;
    case 'fairness_court': return <FairnessCourt beat={beat}/>;
    case 'personalized_defeat': return <PersonalizedDefeat beat={beat}/>;
    case 'status_fossil': return <StatusFossil/>;
    case 'profile_stamp': return <ProfileStamp/>;
    case 'anti_academic_paradox': return <AntiAcademicParadox/>;
    case 'scoreboard_loop': return <ScoreboardLoop beat={beat}/>;
    case 'self_discrepancy': return <SelfDiscrepancy/>;
    case 'unreachable_self': return <UnreachableSelf/>;
    case 'time_distance': return <TimeDistance beat={beat}/>;
    case 'past_rescue': return <PastRescue beat={beat}/>;
    case 'rank_internalization': return <RankInternalization beat={beat}/>;
    case 'exam_hall_empty': return <ExamHallEmpty beat={beat}/>;
    case 'ending_mirror': return <EndingMirror beat={beat}/>;
    case 'ending_ghost': return <EndingGhost beat={beat}/>;
    case 'ending_black': return <EndingBlack/>;
    default: return <Scene><Headline>{beat.visual}</Headline></Scene>;
  }
};
