import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const src=path.join(here,'bootstrap.mjs');
const dst=path.join(here,'bootstrap-fixed.mjs');
let s=fs.readFileSync(src,'utf8');
const start=s.indexOf('const index=`');
const endMarker="`;\nfs.writeFileSync(path.join(root,'src/index.tsx'),index);";
const end=s.indexOf(endMarker,start);
if(start<0||end<0) throw new Error('V41 renderer template block not found');
let block=s.slice(start,end);
block=block.replace(/(?<!\\)\$\{/g,'\\${');
block=block.replace('\\${cases}','${cases}');
s=s.slice(0,start)+block+s.slice(end);
fs.writeFileSync(dst,s);
await import(pathToFileURL(dst).href+'?v='+Date.now());
