import '@fontsource/noto-sans-jp/400.css';
import '@fontsource/noto-sans-jp/700.css';
import {Circle,Line,Node,Rect,Txt,makeScene2D} from '@motion-canvas/2d';
import {all,createRef,easeInOutCubic,easeOutCubic,sequence,waitFor} from '@motion-canvas/core';
import {C,FONT,MOTION} from './theme';
export type Beat={id:string;kind:string;headline:string;labels:string[];narration:string};
export type Chapter={slug:string;title:string;beats:Beat[]};
function chunks(text:string){const ss=text.split(/(?<=[。！？])/).map(x=>x.trim()).filter(Boolean);const out:string[]=[];for(const s of ss){if(s.length<=36){out.push(s);continue;}const ps=s.split(/(?<=[、，])/).map(x=>x.trim()).filter(Boolean);let b='';for(const p of ps){if((b+p).length>36&&b){out.push(b);b=p}else b+=p}if(b)out.push(b)}return out.length?out:[text]}
function Person({x=0,y=0,shirt=C.wine,scale=1,label=''}:{x?:number;y?:number;shirt?:string;scale?:number;label?:string}){return <Node x={x} y={y} scale={scale}><Circle y={-78} width={66} height={66} fill={'#d6ae91'}/><Rect width={104} height={132} radius={28} fill={shirt}/><Rect x={-31} y={102} width={24} height={82} radius={12} fill={'#433743'}/><Rect x={31} y={102} width={24} height={82} radius={12} fill={'#433743'}/>{label?<Txt y={168} text={label} fontFamily={FONT} fontWeight={700} fontSize={23} fill={C.paper}/>:null}</Node>}
function Card({ref,x,y,text,stroke=C.line,w=300,h=92,fill=C.surface2,size=26}:{ref?:any;x:number;y:number;text:string;stroke?:string;w?:number;h?:number;fill?:string;size?:number}){return <Rect ref={ref} x={x} y={y} width={w} height={h} radius={20} fill={fill} stroke={stroke} lineWidth={4}><Txt text={text} width={w-26} textAlign={'center'} textWrap fontFamily={FONT} fontWeight={700} fontSize={size} fill={fill===C.paper?C.ink:C.paper}/></Rect>}
function heading(g:Node,b:Beat){g.add(<Txt y={-350} width={1540} textAlign={'center'} textWrap text={b.headline} fontFamily={FONT} fontWeight={700} fontSize={52} fill={C.paper}/>)}
function build(g:Node,b:Beat){const k=b.kind;const r:any={kind:k};heading(g,b);
if(k==='book_crowd'){r.book=createRef<Rect>();r.stage=createRef<Rect>();r.people=[0,1,2,3,4,5,6,7].map(()=>createRef<Circle>());g.add(<Node y={55}><Rect ref={r.book} x={-510} width={430} height={510} radius={24} fill={'#21151e'} stroke={C.wine} lineWidth={7}><Txt y={-90} text={'IN THE'} fontFamily={FONT} fontWeight={700} fontSize={34} fill={C.gold}/><Txt y={-10} text={'MEGACHURCH'} fontFamily={FONT} fontWeight={700} fontSize={42} fill={C.paper}/><Txt y={85} text={'着想'} fontFamily={FONT} fontWeight={700} fontSize={30} fill={C.muted}/></Rect><Rect ref={r.stage} x={390} y={-30} width={650} height={300} radius={120} fill={'#241621'} stroke={C.gold} lineWidth={5}/>{r.people.map((p:any,i:number)=><Circle key={String(i)} ref={p} x={120+(i%4)*170} y={140+Math.floor(i/4)*105} width={72} height={72} fill={i%2?C.paper:C.cyan} opacity={0.25}/>)}</Node>)}
else if(k==='ritual_words'){r.words=b.labels.map(()=>createRef<Rect>());r.center=createRef<Circle>();const pts=[[-520,-110],[-250,180],[40,-150],[330,170],[580,-80]];g.add(<Node y={50}><Circle ref={r.center} width={210} height={210} fill={C.wine} stroke={C.gold} lineWidth={6}><Txt text={'推し'} fontFamily={FONT} fontWeight={700} fontSize={48} fill={C.paper}/></Circle>{r.words.map((x:any,i:number)=>Card({ref:x,x:pts[i][0],y:pts[i][1],text:b.labels[i],stroke:i%2?C.gold:C.cyan,w:250}))}</Node>);r.words.forEach((x:any)=>x().opacity(0))}
else if(['question_compare','labels_dissolve','us_them','double_edge'].includes(k)){r.left=createRef<Rect>();r.right=createRef<Rect>();r.mid=createRef<Circle>();const l=k==='question_compare'?'宗教':k==='labels_dissolve'?'宗教':k==='us_them'?'我々':'救う';const rr=k==='question_compare'?'推し活':k==='labels_dissolve'?'推し活':k==='us_them'?'彼ら':'縛る';g.add(<Node y={45}><Rect ref={r.left} x={-430} width={650} height={430} radius={40} fill={'#211620'} stroke={k==='us_them'?C.cyan:C.gold} lineWidth={6}><Txt text={l} fontFamily={FONT} fontWeight={700} fontSize={54} fill={C.paper}/></Rect><Rect ref={r.right} x={430} width={650} height={430} radius={40} fill={'#211620'} stroke={k==='double_edge'?C.red:C.wine} lineWidth={6}><Txt text={rr} fontFamily={FONT} fontWeight={700} fontSize={54} fill={C.paper}/></Rect><Circle ref={r.mid} width={135} height={135} fill={C.paper} scale={0.2} opacity={0}><Txt text={k==='labels_dissolve'?'人間':'?'} fontFamily={FONT} fontWeight={700} fontSize={34} fill={C.ink}/></Circle></Node>)}
else if(['human_source','sacred_system','ritual_loop','big_story','capabilities','choose_belief'].includes(k)){r.center=createRef<Circle>();r.nodes=b.labels.slice(0,8).map(()=>createRef<Rect>());r.lines=[];const n=r.nodes.length;g.add(<Node y={55}><Circle ref={r.center} width={190} height={190} fill={k==='big_story'?C.gold:C.wine} stroke={C.paper} lineWidth={5}><Txt text={k==='human_source'?'人間':k==='big_story'?'私':k==='choose_belief'?'私':'中心'} fontFamily={FONT} fontWeight={700} fontSize={38} fill={k==='big_story'?C.ink:C.paper}/></Circle>{r.nodes.map((x:any,i:number)=>{const a=-Math.PI*.95+i*(Math.PI*1.9/Math.max(1,n-1)),px=Math.cos(a)*610,py=Math.sin(a)*245,l=createRef<Line>();r.lines.push(l);return <Node key={String(i)}><Line ref={l} points={[[0,0],[px,py]]} stroke={i%2?C.gold:C.cyan} lineWidth={5} end={0}/>{Card({ref:x,x:px,y:py,text:b.labels[i],stroke:i%2?C.gold:C.cyan,w:250,h:76,size:22})}</Node>})}</Node>);r.nodes.forEach((x:any)=>x().opacity(0))}
else if(k==='cta_lens'){r.beam=createRef<Line>();r.rays=b.labels.map(()=>createRef<Line>());r.words=b.labels.map(()=>createRef<Txt>());const ys=[-150,-50,50,150];g.add(<Node y={45}><Line ref={r.beam} points={[[ -650,0],[-80,0]]} stroke={C.paper} lineWidth={10} end={0}/><Rect width={150} height={150} rotation={45} fill={C.surface2} stroke={C.gold} lineWidth={5}/>{r.rays.map((x:any,i:number)=><Line key={String(i)} ref={x} points={[[80,0],[600,ys[i]]]} stroke={[C.wine,C.gold,C.cyan,C.violet][i]} lineWidth={6} end={0}/>) }{r.words.map((x:any,i:number)=><Txt key={String(i)} ref={x} x={650} y={ys[i]} text={b.labels[i]} fontFamily={FONT} fontWeight={700} fontSize={28} fill={C.paper} opacity={0}/>)}</Node>)}
else if(['sacred_transform','profanation'].includes(k)){r.object=createRef<Rect>();r.halo=createRef<Circle>();r.guard=createRef<Line>();g.add(<Node y={55}><Circle ref={r.halo} width={470} height={470} fill={'rgba(212,170,100,0.05)'} stroke={C.gold} lineWidth={4} scale={0.25} opacity={0}/><Rect ref={r.object} width={320} height={230} radius={20} fill={C.paper} rotation={-3}><Txt text={k==='profanation'?'大切なもの':'ただの物'} fontFamily={FONT} fontWeight={700} fontSize={38} fill={C.ink}/></Rect><Line ref={r.guard} points={[[ -620,210],[620,210]]} stroke={C.red} lineWidth={8} end={0}/></Node>)}
else if(['relic_sequence','sacred_examples','story_stack','private_norm','belief_ladder','meaning_triptych','taste_dogma','question_cards','life_choices'].includes(k)){r.cards=b.labels.slice(0,7).map(()=>createRef<Rect>());r.path=createRef<Line>();const n=r.cards.length,start=-Math.min(620,(n-1)*155/2);g.add(<Node y={55}><Line ref={r.path} points={[[ -650,170],[650,170]]} stroke={C.line} lineWidth={5} end={0}/>{r.cards.map((x:any,i:number)=>Card({ref:x,x:start+i*(n>1?Math.min(310,1240/(n-1)):0),y:-60+(i%2)*70,text:b.labels[i],stroke:i===n-1?C.gold:(i%2?C.wine:C.cyan),w:n>=6?190:250,h:150,size:n>=6?21:24}))}</Node>);r.cards.forEach((x:any)=>{x().opacity(0);x().y(x().y()+60)})}
else if(['rookie_stage','venue_strangers','sync_wave','arena_success','calendar_return'].includes(k)){r.stage=createRef<Rect>();r.hero=createRef<Node>();r.people=[0,1,2,3,4,5,6,7,8,9,10,11].map(()=>createRef<Circle>());r.light=createRef<Circle>();g.add(<Node y={45}><Rect ref={r.stage} y={90} width={1200} height={360} radius={38} fill={'#20141d'} stroke={C.line} lineWidth={5}/><Circle ref={r.light} y={-20} width={330} height={330} fill={'rgba(212,170,100,0.10)'} opacity={0}/><Node ref={r.hero}>{Person({x:0,y:40,shirt:C.wine,scale:.76,label:k==='arena_success'?'推し':k==='calendar_return'?'日常へ':'ステージ'})}</Node>{r.people.map((x:any,i:number)=><Circle key={String(i)} ref={x} x={-650+(i%6)*260} y={260+Math.floor(i/6)*78} width={64} height={64} fill={k==='sync_wave'?(i%2?C.gold:C.cyan):C.paper} opacity={k==='rookie_stage'?(i<3?.7:.12):.38}/>)}</Node>)}
else if(k==='collective'){r.rings=[0,1,2,3].map(()=>createRef<Circle>());r.word=createRef<Txt>();g.add(<Node y={55}>{r.rings.map((x:any,i:number)=><Circle key={String(i)} ref={x} width={220+i*190} height={220+i*190} stroke={[C.wine,C.gold,C.cyan,C.violet][i]} lineWidth={7} opacity={.12}/>) }<Txt ref={r.word} text={'個人'} fontFamily={FONT} fontWeight={700} fontSize={64} fill={C.paper}/></Node>)}
else if(k==='research_sync'){r.card=createRef<Rect>();r.bars=[0,1,2,3].map(()=>createRef<Rect>());g.add(<Node y={45}><Rect ref={r.card} x={-420} width={650} height={460} radius={30} fill={C.paper} stroke={C.gold} lineWidth={6}><Txt y={-145} text={'Mogan, Fischer & Bulbulia'} fontFamily={FONT} fontWeight={700} fontSize={30} fill={C.ink}/><Txt y={-65} text={'2017 / JESP'} fontFamily={FONT} fontSize={26} fill={C.ink}/><Txt y={40} text={'42 studies'} fontFamily={FONT} fontWeight={700} fontSize={50} fill={C.wine}/><Txt y={115} text={'N = 4,327'} fontFamily={FONT} fontWeight={700} fontSize={40} fill={C.ink}/></Rect>{r.bars.map((x:any,i:number)=><Rect key={String(i)} ref={x} x={160+i*160} y={160} width={100} height={20} offsetY={1} fill={[C.wine,C.gold,C.cyan,C.violet][i]}><Txt y={-40} text={['協力','結束','認知','感情'][i]} fontFamily={FONT} fontWeight={700} fontSize={22} fill={C.paper}/></Rect>)}</Node>)}
else if(k==='life_timeline'){r.a=createRef<Line>();r.b=createRef<Line>();r.marks=b.labels.map(()=>createRef<Circle>());g.add(<Node y={45}><Txt x={-690} y={-110} text={'推し'} fontFamily={FONT} fontWeight={700} fontSize={30} fill={C.gold}/><Txt x={-690} y={130} text={'自分'} fontFamily={FONT} fontWeight={700} fontSize={30} fill={C.cyan}/><Line ref={r.a} points={[[ -590,-110],[620,-110]]} stroke={C.gold} lineWidth={8} end={0}/><Line ref={r.b} points={[[ -590,130],[620,130]]} stroke={C.cyan} lineWidth={8} end={0}/>{r.marks.map((x:any,i:number)=><Node key={String(i)}><Circle ref={x} x={-430+i*300} y={i%2?-110:130} width={56} height={56} fill={i%2?C.gold:C.cyan} opacity={0}/><Txt x={-430+i*300} y={i%2?-35:205} text={b.labels[i]} fontFamily={FONT} fontSize={22} fill={C.paper}/></Node>)}</Node>)}
else if(['modern_objects','domains'].includes(k)){r.panels=b.labels.slice(0,8).map(()=>createRef<Rect>());g.add(<Node y={55}>{r.panels.map((x:any,i:number)=>Card({ref:x,x:-560+(i%4)*375,y:-120+Math.floor(i/4)*220,text:b.labels[i],stroke:[C.wine,C.gold,C.cyan,C.violet][i%4],w:320,h:160,size:26}))}</Node>);r.panels.forEach((x:any)=>x().opacity(0))}
else if(k==='meaning_core'){r.center=createRef<Circle>();r.rings=[0,1,2].map(()=>createRef<Circle>());r.words=b.labels.map(()=>createRef<Txt>());g.add(<Node y={55}>{r.rings.map((x:any,i:number)=><Circle key={String(i)} ref={x} width={260+i*220} height={260+i*220} stroke={[C.gold,C.cyan,C.wine][i]} lineWidth={7} opacity={.10}/>) }<Circle ref={r.center} width={220} height={220} fill={C.paper}><Txt text={'意味'} fontFamily={FONT} fontWeight={700} fontSize={58} fill={C.ink}/></Circle>{r.words.map((x:any,i:number)=><Txt key={String(i)} ref={x} x={-520+i*260} y={250-(i%2)*60} text={b.labels[i]} fontFamily={FONT} fontWeight={700} fontSize={24} fill={C.paper} opacity={0}/>)}</Node>)}
else{r.box=createRef<Rect>();g.add(<Rect ref={r.box} y={50} width={1300} height={420} radius={35} fill={C.surface2} stroke={C.wine} lineWidth={6}><Txt text={b.labels.join(' ・ ')} width={1100} textWrap textAlign={'center'} fontFamily={FONT} fontWeight={700} fontSize={36} fill={C.paper}/></Rect>)}return r}
function* animate(b:Beat,r:any,d:number){const t=Math.min(.6,Math.max(.28,d*.08)),q=Math.min(.24,Math.max(.08,d*.025)),k=b.kind;
if(k==='book_crowd'){yield* all(r.book().rotation(-2,t),r.stage().scale(1.05,t).to(1,t));yield* sequence(q,...r.people.map((x:any)=>x().opacity(.75,t)));yield* r.stage().stroke(C.wine,t)}
else if(k==='ritual_words'){yield* sequence(q,...r.words.map((x:any)=>x().opacity(1,t)));yield* r.center().scale(1.12,t).to(1,t)}
else if(['question_compare','labels_dissolve','us_them','double_edge'].includes(k)){yield* all(r.left().x(-500,t),r.right().x(500,t));yield* r.mid().opacity(1,t);yield* r.mid().scale(1,t,easeOutCubic);if(k==='labels_dissolve')yield* all(r.left().opacity(.28,t),r.right().opacity(.28,t));if(k==='us_them')yield* all(r.left().x(-570,t),r.right().x(570,t))}
else if(['human_source','sacred_system','ritual_loop','big_story','capabilities','choose_belief'].includes(k)){yield* sequence(q,...r.lines.map((x:any)=>x().end(1,t)),...r.nodes.map((x:any)=>x().opacity(1,t)));yield* r.center().scale(1.08,t).to(1,t)}
else if(k==='cta_lens'){yield* r.beam().end(1,t);yield* sequence(q,...r.rays.map((x:any)=>x().end(1,t)));yield* sequence(q,...r.words.map((x:any)=>x().opacity(1,t)))}
else if(['sacred_transform','profanation'].includes(k)){yield* all(r.halo().opacity(.75,t),r.halo().scale(1,t));yield* r.object().stroke(C.gold,t);yield* r.guard().end(1,t)}
else if(['relic_sequence','sacred_examples','story_stack','private_norm','belief_ladder','meaning_triptych','taste_dogma','question_cards','life_choices'].includes(k)){yield* r.path().end(1,t);yield* sequence(q,...r.cards.map((x:any)=>all(x().opacity(1,t),x().y(x().y()-60,t,easeOutCubic))));const last=r.cards[r.cards.length-1];if(last)yield* last().scale(1.08,t).to(1,t)}
else if(['rookie_stage','venue_strangers','sync_wave','arena_success','calendar_return'].includes(k)){if(k==='sync_wave'){yield* sequence(q,...r.people.map((x:any,i:number)=>x().y(220+(i%2)*22,t)));yield* all(...r.people.map((x:any)=>x().opacity(.9,t)),r.light().opacity(.65,t))}else if(k==='arena_success'){yield* all(r.stage().width(1580,t*1.5),r.light().opacity(.65,t),r.light().scale(1.5,t));yield* sequence(q,...r.people.map((x:any)=>x().opacity(.9,t)))}else if(k==='calendar_return'){yield* all(r.stage().opacity(.35,t),r.hero().x(-500,t*1.5));yield* sequence(q,...r.people.map((x:any)=>x().opacity(.12,t)))}else{yield* r.light().opacity(.5,t);yield* sequence(q,...r.people.map((x:any)=>x().opacity(.75,t)))}}
else if(k==='collective'){yield* sequence(q,...r.rings.map((x:any,i:number)=>all(x().opacity(.55-i*.08,t),x().scale(1.04,t).to(1,t))));r.word().text('我々');yield* r.word().scale(1.18,t).to(1,t)}
else if(k==='research_sync'){yield* r.card().x(-480,t);yield* sequence(q,...r.bars.map((x:any,i:number)=>x().height(120+i*55,t*1.2)))}
else if(k==='life_timeline'){yield* all(r.a().end(1,t*1.3),r.b().end(1,t*1.3));yield* sequence(q,...r.marks.map((x:any)=>x().opacity(1,t)))}
else if(['modern_objects','domains'].includes(k)){yield* sequence(q,...r.panels.map((x:any)=>x().opacity(1,t)));yield* all(...r.panels.map((x:any,i:number)=>x().y(x().y()+(i%2?15:-15),t)))}
else if(k==='meaning_core'){yield* sequence(q,...r.rings.map((x:any)=>x().opacity(.5,t)));yield* sequence(q,...r.words.map((x:any)=>x().opacity(1,t)));yield* r.center().scale(1.12,t).to(1,t)}
else yield* r.box().scale(1.04,t).to(1,t);const used=Math.min(d*.58,t*5+q*8);yield* waitFor(Math.max(.05,d-used))}
function* subtitleFlow(ref:any,text:string,d:number){const cs=chunks(text),total=Math.max(1,cs.reduce((s,c)=>s+c.length,0));for(const c of cs){ref().text(c);yield* waitFor(Math.max(.34,d*(c.length/total)))}}
export function makeProductionScene(chapter:Chapter,timings:readonly number[]){return makeScene2D(function*(view){view.fill(C.bg);const contentLayer=createRef<Node>();const subtitleLayer=createRef<Node>();const subtitle=createRef<Txt>();const progress=createRef<Rect>();view.add(<><Rect width={1810} height={930} radius={42} fill={C.surface}/><Node ref={contentLayer}/><Txt x={-760} y={-470} width={1400} textAlign={'left'} text={chapter.title} fontFamily={FONT} fontWeight={700} fontSize={27} fill={C.muted}/><Rect y={503} width={1810} height={16} fill={'#120d13'} radius={8}><Rect ref={progress} x={-905} width={1} height={16} fill={C.wine} radius={8} offsetX={-1}/></Rect><Node ref={subtitleLayer}><Rect y={425} width={1740} height={132} radius={22} fill={'rgba(0,0,0,0.90)'}><Txt ref={subtitle} width={1580} text={''} textAlign={'center'} textWrap fontFamily={FONT} fontWeight={700} fontSize={38} lineHeight={54} fill={C.paper}/></Rect></Node></>);const total=Math.max(1,chapter.beats.length);for(let i=0;i<chapter.beats.length;i++){const beat=chapter.beats[i],duration=Math.max(1.2,Number(timings[i]??8)),group=createRef<Node>();contentLayer().add(<Node ref={group} opacity={0} scale={.985} y={-18}/>);const refs=build(group(),beat);yield* all(group().opacity(1,MOTION.beat,easeOutCubic),group().scale(1,MOTION.beat,easeOutCubic));const vd=Math.max(.8,duration-MOTION.exit);yield* all(animate(beat,refs,vd),subtitleFlow(subtitle,beat.narration,vd),progress().width(1810*((i+1)/total),vd,easeInOutCubic));yield* group().opacity(0,MOTION.exit)}subtitle().text('');yield* waitFor(.2)})}