import React from 'react';
export const K={paper:'#f3ede1',ink:'#15232c',gold:'#c8a15d',red:'#aa5754',teal:'#70a097',blue:'#5d7f96',green:'#6e8f73',orange:'#b47d55',gray:'#7c858b'};
export const q=(v:number)=>Math.max(0,Math.min(1,v));
export const ease=(p:number)=>{const x=q(p);return x*x*(3-2*x)};
const T=({x=0,y=0,t,s=32,c=K.paper,a='middle',o=1}:{x?:number;y?:number;t:string;s?:number;c?:string;a?:'start'|'middle'|'end';o?:number})=><text x={x} y={y} textAnchor={a} fontFamily="Noto Sans JP,sans-serif" fontWeight={760} fontSize={s} fill={c} opacity={o}>{t}</text>;
const R=({x,y,w,h,c=K.paper,rx=18,o=1,stroke,sw=0}:{x:number;y:number;w:number;h:number;c?:string;rx?:number;o?:number;stroke?:string;sw?:number})=><rect x={x} y={y} width={w} height={h} rx={rx} fill={c} opacity={o} stroke={stroke} strokeWidth={sw}/>;
const Arrow=({x1,y1,x2,y2,c=K.gold,p=1}:{x1:number;y1:number;x2:number;y2:number;c?:string;p?:number})=><g opacity={q(p)}><line x1={x1} y1={y1} x2={x1+(x2-x1)*q(p)} y2={y1+(y2-y1)*q(p)} stroke={c} strokeWidth="14" strokeLinecap="round"/><circle cx={x1+(x2-x1)*q(p)} cy={y1+(y2-y1)*q(p)} r="19" fill={c}/></g>;
const labels:Record<string,string>={
 'office-worker':'45歳 課長','friend-message':'大学時代の友人','job-posting':'年収800〜1000万円','career-form':'専門スキル','internal-tasks':'社内調整・予算・報告','market-question':'会社の外でいくら？','future-value':'未来の時間','young-worker':'25歳','human-capital':'人的資本','training-investment':'教育・訓練','time-horizon':'回収できる時間','potential-interview':'可能性を買う','age-shift':'将来性 → 実績','accumulation-question':'20年で何を蓄積？',
 'manager-day':'社内では重要','general-capital':'持ち運べる能力','firm-specific':'企業特殊的人的資本','internal-map':'社内の地図','company-gate':'会社の門','two-currencies':'外貨 / 社内通貨','salary-slip':'給与明細','mixed-price':'一枚の値札','market-sort':'買う / 買わない',
 'showa-worker':'昭和の若手','seniority-system':'年功賃金','deferred-wage':'若く低く・後で高く','training-loop':'長期雇用×訓練','oecd-curve':'勤続年数と賃金','family-costs':'住宅ローン・教育費','young-hire':'400万円で育てる','midcareer-hire':'750万円の根拠','proof-pressure':'高い値札には証明','internal-vs-market':'社内価格 / 市場価格','casino-chip':'社内チップ','outside-store':'外では使えない',
 'wage-data':'2025年 転職賃金','age-40':'40〜44歳 47.7%','age-45':'45〜49歳 41.1%','age-50':'50〜54歳 増26.5% 減44.7%','fork':'40代は分岐点','candidate-a':'役職と年数','candidate-b':'成果の仕組み','reproducibility':'再現性','brand-mask':'会社名を外す','portable-result':'別の会社でも起こせる','ai-change':'AIで仕事が変わる','metaskills':'論理・批判・対話','automation-risk':'熟練≠永続価値','problem-solving':'問題を定義し動かす','logo-off':'会社名を消す','i-can':'私はこれをできます',
 'employee-badge':'社員証','doors-open':'社内で開く扉','badge-down':'カードを置く','two-price-tags':'社内価格 / 市場価格','subtract-list':'会社・役職・勤続を引く','portable-core':'残るもの','outside-mirror':'外から自分を見る','value-separation':'会社の価値 / 自分の価値'
};
const tag=(k:string)=>labels[k]??k;

export const MarketSubject=({kind,p}:{kind:string;p:number})=>{
 const e=ease(p),c=kind.includes('ai')?K.teal:kind.includes('market')||kind.includes('question')?K.red:kind.includes('future')||kind.includes('training')?K.gold:K.blue;
 if(kind==='two-currencies'||kind==='internal-vs-market'||kind==='two-price-tags'||kind==='value-separation')return <g><R x={-390} y={-210} w={330} h={420} c={K.blue}/><R x={60} y={-210} w={330} h={420} c={K.red}/><T x={-225} y={-5} t={tag(kind).split(' / ')[0]} s={34}/><T x={225} y={-5} t={tag(kind).split(' / ')[1]||'市場'} s={34}/><Arrow x1={-20} y1={0} x2={20} y2={0} c={K.gold} p={e}/></g>;
 if(kind==='age-shift'||kind==='time-horizon'||kind==='wage-data'||kind==='oecd-curve')return <g><line x1="-390" y1="220" x2="390" y2="220" stroke={K.paper} strokeWidth="8"/><line x1="-390" y1="220" x2="-390" y2="-230" stroke={K.paper} strokeWidth="8"/><path d="M-350 160 C-150 120 40 20 330 -150" fill="none" stroke={K.gold} strokeWidth="16" strokeDasharray={(900*e)+' 900'}/><path d="M-350 -130 C-110 -90 100 30 330 160" fill="none" stroke={K.red} strokeWidth="12" strokeDasharray={(900*e)+' 900'}/><T x={0} y={-275} t={tag(kind)} s={42}/></g>;
 if(kind==='age-40'||kind==='age-45'||kind==='age-50'||kind==='fork')return <g><T y={-260} t={tag(kind)} s={48} c={kind==='age-50'?K.red:K.paper}/>{[0,1,2,3].map(i=><R key={i} x={-360+i*190} y={170-(i+1)*75} w={130} h={(i+1)*75} c={i===3?K.red:K.teal} o={.45+.12*i}/>)}</g>;
 if(kind==='casino-chip')return <g>{[0,1,2,3,4].map(i=><circle key={i} cx={-240+i*120} cy={80-Math.abs(2-i)*48} r={72} fill={i%2?K.gold:K.red} stroke={K.paper} strokeWidth="10" opacity={q(e*1.4-i*.12)}/>) }<T y={-190} t="社内で貯めたチップ" s={42}/></g>;
 if(kind==='internal-map')return <g>{[0,1,2,3,4,5].map(i=><circle key={i} cx={-300+(i%3)*300} cy={-120+Math.floor(i/3)*260} r={65} fill={[K.blue,K.teal,K.gold][i%3]}/>) }{[[0,1],[1,2],[0,3],[1,4],[2,5],[3,4],[4,5]].map((a,i)=><line key={i} x1={-300+(a[0]%3)*300} y1={-120+Math.floor(a[0]/3)*260} x2={-300+(a[1]%3)*300} y2={-120+Math.floor(a[1]/3)*260} stroke={K.paper} strokeWidth="8" opacity={e}/>) }<T y={-310} t="社内の誰に通せば動くか" s={36}/></g>;
 if(kind==='market-sort'||kind==='subtract-list')return <g><T y={-280} t={tag(kind)} s={44}/>{['会社ブランド','役職','勤続年数','社内人脈','持ち運べる能力'].map((t,i)=><g key={t} opacity={q(e*1.5-i*.14)}><R x={-370} y={-180+i*96} w={740} h={70} c={i===4?K.teal:i<4?K.gray:K.blue} o={i===4?.95:.55}/><T y={-133+i*96} t={t} s={28}/>{kind==='subtract-list'&&i<4?<line x1="-330" y1={-145+i*96} x2="330" y2={-145+i*96} stroke={K.red} strokeWidth="12"/>:null}</g>)}</g>;
 if(kind==='candidate-a'||kind==='candidate-b')return <g><R x={-350} y={-230} w={700} h={460} c={kind==='candidate-a'?'#344652':'#244a45'} stroke={kind==='candidate-a'?K.gray:K.gold} sw={8}/><T y={-135} t={kind==='candidate-a'?'課長・15年・部下12名':'工程を再設計・成果を再現'} s={35}/><T y={-40} t={kind==='candidate-a'?'前の会社での地位':'別環境でも使える方法'} s={30} c={kind==='candidate-a'?K.paper:K.gold}/>{[0,1,2].map(i=><R key={i} x={-250} y={45+i*70} w={500-(i*50)} h={22} c={kind==='candidate-a'?K.gray:K.teal}/>)}</g>;
 if(kind==='metaskills'||kind==='problem-solving'||kind==='portable-core')return <g><circle r="250" fill="#17333c" stroke={K.teal} strokeWidth="10"/>{['論理','批判','対話','問題定義','再現性'].map((t,i)=>{const a=-Math.PI/2+i*Math.PI*2/5;return <g key={t} opacity={q(e*1.5-i*.12)}><circle cx={Math.cos(a)*240} cy={Math.sin(a)*190} r="70" fill={i%2?K.gold:K.blue}/><T x={Math.cos(a)*240} y={Math.sin(a)*190+10} t={t} s={24}/></g>})}<T y={10} t={tag(kind)} s={34}/></g>;
 if(kind==='brand-mask'||kind==='logo-off'||kind==='badge-down'||kind==='employee-badge'||kind==='doors-open')return <g><R x={-260} y={-180} w={520} h={360} c="#d8d8d2" stroke={K.gray} sw={8}/><circle cx="-110" cy="-30" r="70" fill={K.blue}/><R x={10} y={-85} w={180} h={30} c={K.gray}/><R x={10} y={-25} w={140} h={24} c={K.gray}/><T y={260} t={tag(kind)} s={42} c={kind==='badge-down'||kind==='logo-off'?K.red:K.paper}/>{kind==='logo-off'||kind==='brand-mask'?<line x1="-300" y1="-210" x2="300" y2="210" stroke={K.red} strokeWidth="18" opacity={e}/>:null}</g>;
 return <g opacity={q(.15+e)}><R x={-360} y={-220} w={720} h={440} c="#263a45" stroke={c} sw={10}/><circle cx="-240" cy="-70" r="72" fill={c}/><T x={-120} y={-55} t={tag(kind)} s={38} a="start"/>{[0,1,2,3].map(i=><R key={i} x={-250} y={45+i*55} w={520-i*55} h={18} c={i===0?K.gold:K.gray} o={.8-i*.12}/>)}</g>;
};