import React from 'react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';

const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const p=(f:number,a=0,b=24)=>interpolate(f,[a,b],[0,1],clamp);
const lerp=(f:number,a:number,b:number,c:number,d:number)=>interpolate(f,[a,b],[c,d],clamp);
const font='"Noto Sans CJK JP",sans-serif';
const C={paper:'#f2eee5',muted:'#a2a7ad',ink:'#040608',blue:'#7ba4c5',cyan:'#75c7c8',amber:'#d8ac64',red:'#bd625d',green:'#82a983',violet:'#9b89bd',pink:'#c989a3',grey:'#41484f'};

const Scene=({children,tone='night'}:{children:React.ReactNode;tone?:'night'|'blue'|'warm'|'black'|'rose'})=>{const bg=tone==='blue'?'linear-gradient(145deg,#06131d,#102a37 57%,#020406)':tone==='warm'?'linear-gradient(145deg,#180e0b,#35231b 57%,#030303)':tone==='rose'?'linear-gradient(145deg,#160a10,#2c1822 55%,#040304)':tone==='black'?'#020304':'linear-gradient(145deg,#05070a,#12171c 57%,#030405)';return <AbsoluteFill style={{background:bg,color:C.paper,overflow:'hidden',fontFamily:font}}>{children}<AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,transparent 30%,rgba(0,0,0,.25) 72%,rgba(0,0,0,.82) 100%)',pointerEvents:'none'}}/></AbsoluteFill>};
const Headline=({text}:{text:string})=><div style={{position:'absolute',left:105,top:70,right:105,fontSize:50,fontWeight:950,letterSpacing:.6,textShadow:'0 5px 26px rgba(0,0,0,.78)'}}>{text}</div>;
const Pill=({x,y,text,color=C.cyan,delay=0}:{x:number;y:number;text:string;color?:string;delay?:number})=>{const f=useCurrentFrame();const q=p(f,delay,delay+22);return <div style={{position:'absolute',left:x,top:y,padding:'13px 22px',borderRadius:999,border:`2px solid ${color}66`,background:'rgba(4,8,12,.80)',fontSize:28,fontWeight:900,color,opacity:q,transform:`translateY(${(1-q)*18}px) scale(${.94+.06*q})`}}>{text}</div>};
const Face=({x,y,size=150,color=C.blue}:{x:number;y:number;size?:number;color?:string})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,width:size,height:size,borderRadius:'50%',background:`radial-gradient(circle at 42% 34%,${color},#11151a 74%)`,border:`5px solid ${color}88`,boxShadow:`0 0 35px ${color}55`,transform:`translateY(${Math.sin((f+x)/50)*5}px)`}}><div style={{position:'absolute',left:size*.28,top:size*.38,width:size*.12,height:size*.08,borderRadius:20,background:C.ink}}/><div style={{position:'absolute',right:size*.28,top:size*.38,width:size*.12,height:size*.08,borderRadius:20,background:C.ink}}/><div style={{position:'absolute',left:size*.34,top:size*.66,width:size*.32,height:size*.14,borderBottom:`5px solid ${C.paper}`,borderRadius:'0 0 80px 80px'}}/></div>};

export const CrowdGrid=({headline='多数が同じ状態になる',count=14,highlight=0}:{headline?:string;count?:number;highlight?:number})=><Scene tone="rose"><Headline text={headline}/>{Array.from({length:Math.min(28,count)},(_,i)=>{const x=120+(i%7)*255,y=260+Math.floor(i/7)*260;return <Face key={i} x={x} y={y} size={145} color={i===highlight?C.amber:[C.pink,C.cyan,C.violet][i%3]}/>})}</Scene>;

export const ThresholdFloor=({headline='最低ラインが上がる',label='基準',from=50,to=90}:{headline?:string;label?:string;from?:number;to?:number})=>{const f=useCurrentFrame();const value=lerp(f,0,80,from,to);return <Scene tone="black"><Headline text={headline}/><div style={{position:'absolute',left:240,top:340,width:1440,height:420,borderRadius:45,border:'3px solid rgba(255,255,255,.13)',background:'rgba(255,255,255,.03)'}}><div style={{position:'absolute',left:120,right:120,top:250,height:12,background:C.grey}}><div style={{position:'absolute',left:`${Math.min(100,Math.max(0,value))}%`,top:-34,width:72,height:72,borderRadius:'50%',background:C.red,boxShadow:`0 0 30px ${C.red}88`,transform:'translateX(-36px)'}}/></div><div style={{position:'absolute',left:0,right:0,top:90,textAlign:'center',fontSize:72,fontWeight:950}}>{label} {value.toFixed(0)}</div></div></Scene>};

export const MetricAxes=({headline='評価軸が増える',items=['身長','声','知性','年収']}:{headline?:string;items?:string[]})=><Scene tone="blue"><Headline text={headline}/>{items.slice(0,8).map((t,i)=><Pill key={t+i} x={180+(i%4)*420} y={280+Math.floor(i/4)*240} text={t} color={[C.blue,C.cyan,C.green,C.amber,C.violet,C.red,C.pink,C.paper][i%8]} delay={i*5}/>)}</Scene>;

export const ThesisReveal=({text='核心命題',emphasis}:{text?:string;emphasis?:string})=>{const f=useCurrentFrame();const q=p(f,0,40);const [pre,post]=emphasis&&text.includes(emphasis)?text.split(emphasis):[text,''];return <Scene tone="black"><div style={{position:'absolute',left:190,right:190,top:330,textAlign:'center',fontSize:76,fontWeight:950,lineHeight:1.4,opacity:q,transform:`scale(${.94+.06*q})`}}>{pre}{emphasis&&<span style={{color:C.red}}>{emphasis}</span>}{post}</div></Scene>};

export const DualCompare=({headline='二つの価値を比較する',left='左',right='右'}:{headline?:string;left?:string;right?:string})=>{const f=useCurrentFrame();const q=p(f,0,32);return <Scene><Headline text={headline}/><div style={{position:'absolute',left:260,top:300,width:580,height:430,borderRadius:42,border:`3px solid ${C.cyan}66`,background:'rgba(8,20,24,.64)',transform:`translateX(${(1-q)*-120}px)`}}><div style={{position:'absolute',left:0,right:0,top:160,textAlign:'center',fontSize:48,fontWeight:950}}>{left}</div></div><div style={{position:'absolute',left:1080,top:300,width:580,height:430,borderRadius:42,border:`3px solid ${C.red}66`,background:'rgba(24,9,11,.64)',transform:`translateX(${(1-q)*120}px)`}}><div style={{position:'absolute',left:0,right:0,top:160,textAlign:'center',fontSize:48,fontWeight:950}}>{right}</div></div></Scene>};

export const ContextBar=({headline='同じ値でも文脈で意味が変わる',leftAvg=170,rightAvg=190,value=180,unit=''}:{headline?:string;leftAvg?:number;rightAvg?:number;value?:number;unit?:string})=><Scene tone="blue"><Headline text={headline}/>{[[240,leftAvg,C.cyan],[1070,rightAvg,C.red]].map(([x,avg,color],i)=><div key={i} style={{position:'absolute',left:Number(x),top:260,width:620,height:560,borderRadius:35,border:'2px solid rgba(255,255,255,.13)'}}><Pill x={160} y={60} text={`平均 ${avg}${unit}`} color={String(color)}/><div style={{position:'absolute',left:120,bottom:70,width:100,height:Number(avg)*2.1,background:String(color)}}/><div style={{position:'absolute',left:360,bottom:70,width:100,height:value*2.1,background:C.paper}}/><div style={{position:'absolute',left:330,bottom:20,fontSize:34,fontWeight:900}}>{value}{unit}</div></div>)}</Scene>;

export const ScarcityDilution=({headline='普及すると希少性が薄れる',total=100,from=10,to=100,label='普及'}:{headline?:string;total?:number;from?:number;to?:number;label?:string})=>{const f=useCurrentFrame();const count=Math.floor(lerp(f,0,90,from,to));return <Scene><Headline text={headline}/><div style={{position:'absolute',left:220,top:250,width:1480,height:560,display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:12}}>{Array.from({length:Math.min(100,total)},(_,i)=><div key={i} style={{borderRadius:'50%',background:i<count?C.cyan:C.grey,opacity:i<count?.9:.2,boxShadow:i<count?`0 0 12px ${C.cyan}55`:'none'}}/>)}</div><Pill x={720} y={840} text={`${label}: ${Math.min(total,count)} / ${total}`} color={C.cyan}/></Scene>};

export const PositionalCards=({headline='相対的位置が価値になる',items=['高級住宅','名門校','美貌']}:{headline?:string;items?:string[]})=><Scene tone="warm"><Headline text={headline}/>{items.slice(0,4).map((t,i)=><div key={t+i} style={{position:'absolute',left:190+i*420,top:320+i*55,width:300,height:220,borderRadius:32,border:`3px solid ${[C.amber,C.blue,C.violet,C.pink][i%4]}66`,background:'rgba(0,0,0,.35)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:36,fontWeight:950}}>{t}</div>)}</Scene>;

export const OrbitLabels=({headline='評価が細分化する',center='中心',items=['A','B','C','D']}:{headline?:string;center?:string;items?:string[]})=>{const f=useCurrentFrame();return <Scene tone="rose"><Headline text={headline}/><div style={{position:'absolute',left:760,top:350,width:400,height:300,borderRadius:40,border:`4px solid ${C.pink}88`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:54,fontWeight:950}}>{center}</div>{items.slice(0,8).map((t,i)=>{const a=f/90+i/items.length*Math.PI*2;return <Pill key={t+i} x={900+Math.cos(a)*620} y={500+Math.sin(a)*320} text={t} color={[C.cyan,C.amber,C.red,C.violet,C.green,C.paper][i%6]} delay={i*3}/>})}</Scene>};

export const AverageShift=({headline='平均が上がると基準も上がる',oldAvg=50,newAvg=90,subject=89}:{headline?:string;oldAvg?:number;newAvg?:number;subject?:number})=>{const f=useCurrentFrame();const avg=lerp(f,0,90,oldAvg,newAvg);return <Scene tone="black"><Headline text={headline}/><div style={{position:'absolute',left:260,right:260,top:560,height:14,background:C.grey}}><div style={{position:'absolute',left:`${avg}%`,top:-65,width:8,height:150,background:C.red,transform:'translateX(-4px)'}}/><div style={{position:'absolute',left:`${subject}%`,top:-28,width:58,height:58,borderRadius:'50%',background:C.cyan,transform:'translateX(-29px)',boxShadow:`0 0 25px ${C.cyan}88`}}/></div><Pill x={520} y={730} text={`平均 ${avg.toFixed(0)}`} color={C.red}/><Pill x={1080} y={730} text={`対象 ${subject}`} color={C.cyan}/></Scene>};

export const DecimalRanking=({headline='僅差が巨大な意味を持つ',scores=[90.1,90.4,90.7,91.2]}:{headline?:string;scores?:number[]})=>{const f=useCurrentFrame();const sorted=[...scores].sort((a,b)=>b-a);return <Scene tone="blue"><Headline text={headline}/>{sorted.slice(0,6).map((s,i)=>{const q=p(f,i*6,i*6+24);return <div key={s+i} style={{position:'absolute',left:500,top:260+i*105,width:920,height:78,borderRadius:18,background:'rgba(5,15,22,.75)',border:`2px solid ${i===0?C.amber:C.cyan}55`,display:'flex',alignItems:'center',padding:'0 35px',fontSize:38,fontWeight:950,opacity:q,transform:`translateX(${(1-q)*80}px)`}}><span style={{width:120}}>#{i+1}</span><span style={{flex:1}}>候補 {String.fromCharCode(65+i)}</span><span style={{fontSize:54}}>{s.toFixed(1)}</span></div>})}</Scene>};

export const RedQueenTreadmill=({headline='走り続けても順位が変わらない',actors=5,labels=['美容','筋トレ','服','年収']}:{headline?:string;actors?:number;labels?:string[]})=>{const f=useCurrentFrame();return <Scene tone="black"><Headline text={headline}/><div style={{position:'absolute',left:140,right:140,bottom:200,height:26,background:C.grey,overflow:'hidden'}}>{Array.from({length:14},(_,i)=><div key={i} style={{position:'absolute',left:(i*170-f*8)%2100,top:0,width:90,height:26,background:i%2?C.grey:'#69717a'}}/>)}</div>{Array.from({length:Math.min(7,actors)},(_,i)=><div key={i} style={{position:'absolute',left:250+i*260,top:430+Math.sin((f+i*10)/10)*12,width:80,height:170,borderRadius:'40px 40px 12px 12px',background:[C.cyan,C.amber,C.red,C.green,C.violet][i%5]}}/>)}{labels.slice(0,4).map((t,i)=><Pill key={t+i} x={300+i*360} y={760} text={t} color={[C.cyan,C.amber,C.red,C.violet][i%4]} delay={i*5}/>)}</Scene>};

export const SplitWorld=({headline='一つの分岐が二つの人生を作る',real='現実',alternate='もしも'}:{headline?:string;real?:string;alternate?:string})=><Scene tone="blue"><Headline text={headline}/><div style={{position:'absolute',left:260,top:530,width:450,height:10,background:C.paper}}/><div style={{position:'absolute',left:710,top:535,width:620,height:8,background:C.red,transform:'rotate(-22deg)',transformOrigin:'0 50%'}}/><div style={{position:'absolute',left:710,top:535,width:620,height:8,background:C.cyan,transform:'rotate(22deg)',transformOrigin:'0 50%'}}/><Pill x={1320} y={275} text={real} color={C.red}/><Pill x={1320} y={690} text={alternate} color={C.cyan}/></Scene>;

export const MovingGoalpost=({headline='達成してもゴールが逃げる',goal='GOAL',distance=900}:{headline?:string;goal?:string;distance?:number})=>{const f=useCurrentFrame();const x=lerp(f,0,110,650,Math.min(1550,650+distance));return <Scene tone="blue"><Headline text={headline}/><div style={{position:'absolute',left:340,top:570,width:120,height:220,borderRadius:'60px 60px 18px 18px',background:C.paper}}/><div style={{position:'absolute',left:x,top:300,width:26,height:500,background:C.amber}}><div style={{position:'absolute',left:0,top:0,width:250,height:110,background:C.red,clipPath:'polygon(0 0,100% 50%,0 100%)'}}/></div><Pill x={x-60} y={820} text={goal} color={C.amber}/></Scene>};

export type SharedTemplateId='crowd_grid'|'threshold_floor'|'metric_axes'|'thesis_reveal'|'dual_compare'|'context_bar'|'scarcity_dilution'|'positional_cards'|'orbit_labels'|'average_shift'|'decimal_ranking'|'red_queen_treadmill'|'split_world'|'moving_goalpost';

export const SharedTemplateScene=({templateId,params={}}:{templateId:SharedTemplateId;params?:Record<string,unknown>})=>{
  const map:Record<SharedTemplateId,React.ComponentType<any>>={crowd_grid:CrowdGrid,threshold_floor:ThresholdFloor,metric_axes:MetricAxes,thesis_reveal:ThesisReveal,dual_compare:DualCompare,context_bar:ContextBar,scarcity_dilution:ScarcityDilution,positional_cards:PositionalCards,orbit_labels:OrbitLabels,average_shift:AverageShift,decimal_ranking:DecimalRanking,red_queen_treadmill:RedQueenTreadmill,split_world:SplitWorld,moving_goalpost:MovingGoalpost};
  const Component=map[templateId];
  return <Component {...params}/>;
};
