import React from 'react';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';

const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const font='"Noto Sans CJK JP",sans-serif';
const C={paper:'#f3efe7',ink:'#050608',muted:'#98a0a9',cyan:'#72c8cb',blue:'#6e9fc5',red:'#c45d61',amber:'#e0ad61',pink:'#c97f9e',violet:'#9986c8',green:'#7eaa8a',grey:'#323941'};
const p=(f:number,a=0,b=24)=>interpolate(f,[a,b],[0,1],clamp);

const Base=({children,tone='dark'}:{children:React.ReactNode;tone?:'dark'|'rose'|'blue'|'warm'})=>{const f=useCurrentFrame();const bg=tone==='rose'?'linear-gradient(140deg,#16080f,#301521 55%,#030405)':tone==='blue'?'linear-gradient(140deg,#041019,#112a39 55%,#020405)':tone==='warm'?'linear-gradient(140deg,#140c08,#342218 55%,#030405)':'linear-gradient(140deg,#030507,#11171c 55%,#020304)';return <AbsoluteFill style={{background:bg,color:C.paper,overflow:'hidden',fontFamily:font}}><AbsoluteFill style={{transform:`scale(${1.006+Math.sin(f/150)*.006})`}}>{children}</AbsoluteFill><AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,transparent 28%,rgba(0,0,0,.3) 70%,rgba(0,0,0,.86) 100%)',pointerEvents:'none'}}/></AbsoluteFill>};
const H=({children}:{children:React.ReactNode})=><div style={{position:'absolute',left:110,right:110,top:70,fontSize:52,fontWeight:950,letterSpacing:.5,textShadow:'0 5px 26px rgba(0,0,0,.75)'}}>{children}</div>;
const Bubble=({x,y,text,color=C.cyan,delay=0}:{x:number;y:number;text:string;color?:string;delay?:number})=>{const f=useCurrentFrame();const q=p(f,delay,delay+18);return <div style={{position:'absolute',left:x,top:y,padding:'12px 20px',borderRadius:999,background:'rgba(5,9,13,.82)',border:`2px solid ${color}66`,color,fontWeight:900,fontSize:27,opacity:q,transform:`translateY(${(1-q)*18}px) scale(${.92+.08*q})`,boxShadow:`0 10px 30px ${color}16`}}>{text}</div>};

export const SwipeStream=({headline='候補が終わらない',profiles=['A','B','C','D','E'],velocity=1,emphasis=1}:{headline?:string;profiles?:string[];velocity?:number;emphasis?:number})=>{const f=useCurrentFrame();return <Base tone="rose"><H>{headline}</H><div style={{position:'absolute',left:0,right:0,top:210,bottom:110,perspective:1100}}>{Array.from({length:9},(_,i)=>{const loop=((f*velocity*4+i*230)%2100);const z=900-loop;const scale=interpolate(z,[-1200,900],[.34,1.12],clamp);const x=960+Math.sin(i*1.7)*360*scale;const y=515+Math.cos(i*.9)*110*scale;const opacity=interpolate(z,[-1200,-800,500,900],[0,.25,.9,0],clamp);const hot=i%profiles.length===emphasis%profiles.length;return <div key={i} style={{position:'absolute',left:x-155,top:y-220,width:310,height:440,borderRadius:34,background:`linear-gradient(160deg,${hot?'#542238':'#13202a'},#06080b)`,border:`3px solid ${hot?C.pink:C.cyan}66`,boxShadow:`0 26px 70px rgba(0,0,0,.45),0 0 32px ${hot?C.pink:C.cyan}22`,transform:`translateZ(${z}px) scale(${scale}) rotate(${(i%3-1)*2}deg)`,opacity}}><div style={{height:260,borderRadius:'30px 30px 0 0',background:`radial-gradient(circle at 50% 38%,${hot?C.pink:C.blue},#0a0e12 72%)`}}/><div style={{padding:'22px 25px',fontSize:31,fontWeight:950}}>{profiles[i%profiles.length]}</div><div style={{padding:'0 25px',fontSize:22,color:C.muted}}>MATCH  •  92%</div></div>})}</div></Base>};

export const ExtremeValuePool=({headline='母集団が増えるほど極端値が見える',poolSize=100,highlightedTop=5,expectedMax=99,label='候補'}:{headline?:string;poolSize?:number;highlightedTop?:number;expectedMax?:number;label?:string})=>{const f=useCurrentFrame();const shown=Math.min(140,Math.max(12,poolSize));const lit=Math.max(1,Math.round(shown*highlightedTop/Math.max(poolSize,1)));return <Base tone="blue"><H>{headline}</H><div style={{position:'absolute',left:150,right:150,top:245,height:560,display:'grid',gridTemplateColumns:'repeat(14,1fr)',gap:13}}>{Array.from({length:shown},(_,i)=>{const q=p(f,i*.8,i*.8+18);const top=i>=shown-lit;return <div key={i} style={{borderRadius:999,background:top?C.amber:C.grey,opacity:(top?.95:.2)*q,boxShadow:top?`0 0 20px ${C.amber}88`:'none',transform:`scale(${.55+.45*q})`}}/>})}</div><div style={{position:'absolute',right:160,top:320,width:350,height:350,borderRadius:'50%',border:`7px solid ${C.amber}88`,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',background:'rgba(5,8,10,.65)',boxShadow:`0 0 70px ${C.amber}33`}}><div style={{fontSize:24,color:C.muted}}>{label}の最高値</div><div style={{fontSize:96,fontWeight:950,color:C.amber}}>{expectedMax}</div></div></Base>};

export const OpportunityCostFan=({headline='一人を選ぶと、他の可能性が閉じる',options=['A','B','C','D','E','F'],selected=0}:{headline?:string;options?:string[];selected?:number})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const open=spring({fps,frame:f,config:{damping:16,stiffness:90,mass:.8}});return <Base tone="warm"><H>{headline}</H><div style={{position:'absolute',left:880,top:520,width:160,height:160,borderRadius:'50%',background:C.paper,color:C.ink,display:'flex',alignItems:'center',justifyContent:'center',fontSize:34,fontWeight:950,boxShadow:'0 0 55px rgba(255,255,255,.18)'}}>YOU</div>{options.slice(0,8).map((o,i)=>{const a=(-2.5+i*(5/Math.max(1,options.length-1)))*.9;const r=520*open;const x=960+Math.cos(a)*r;const y=600+Math.sin(a)*r*.68;const chosen=i===selected;const fade=chosen?1:interpolate(f,[50,105],[1,.18],clamp);return <React.Fragment key={o+i}><div style={{position:'absolute',left:960,top:600,width:r-70,height:5,background:chosen?C.green:C.red,transform:`rotate(${a}rad)`,transformOrigin:'0 50%',opacity:.55*fade}}/><div style={{position:'absolute',left:x-72,top:y-72,width:144,height:144,borderRadius:'50%',background:chosen?C.green:C.grey,border:`4px solid ${chosen?C.green:C.red}88`,opacity:fade,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,fontWeight:950,boxShadow:chosen?`0 0 40px ${C.green}55`:'none'}}>{o}</div></React.Fragment>})}</Base>};

export const TwoSidedMatchMarket=({headline='恋愛は二方向の市場である',left=['A','B','C','D'],right=['W','X','Y','Z'],matches=[[0,1],[1,0],[2,3]]}:{headline?:string;left?:string[];right?:string[];matches?:Array<[number,number]>})=>{const f=useCurrentFrame();return <Base tone="blue"><H>{headline}</H>{left.slice(0,5).map((t,i)=><div key={'l'+i} style={{position:'absolute',left:230,top:245+i*145,width:150,height:110,borderRadius:26,background:'#10212a',border:`2px solid ${C.cyan}77`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,fontWeight:950}}>{t}</div>)}{right.slice(0,5).map((t,i)=><div key={'r'+i} style={{position:'absolute',right:230,top:245+i*145,width:150,height:110,borderRadius:26,background:'#2a1520',border:`2px solid ${C.pink}77`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32,fontWeight:950}}>{t}</div>)}<svg width="1920" height="1080" style={{position:'absolute',inset:0}}>{matches.map(([a,b],i)=>{const x1=380,y1=300+a*145,x2=1540,y2=300+b*145;const q=p(f,10+i*10,35+i*10);return <line key={i} x1={x1} y1={y1} x2={x1+(x2-x1)*q} y2={y1+(y2-y1)*q} stroke={i%2?C.pink:C.cyan} strokeWidth="7" opacity="0.72"/>})}</svg><Bubble x={755} y={820} text="双方が YES の線だけ成立" color={C.amber}/></Base>};

export const RealVsPossiblePartner=({headline='現実の相手と、未知の可能性は公平に比較できない',realLabel='現実の相手',possibleLabel='まだ会っていない候補',flaws=['洗濯物','返信の癖','機嫌'],dreams=['完璧','未知','可能性']}:{headline?:string;realLabel?:string;possibleLabel?:string;flaws?:string[];dreams?:string[]})=>{const f=useCurrentFrame();const reveal=p(f,18,70);return <Base tone="rose"><H>{headline}</H><div style={{position:'absolute',left:210,top:250,width:650,height:560,borderRadius:44,background:'rgba(14,19,22,.82)',border:`3px solid ${C.cyan}55`}}><div style={{position:'absolute',left:225,top:65,width:200,height:200,borderRadius:'50%',background:`radial-gradient(circle at 45% 38%,${C.cyan},#0a0c0e 70%)`}}/><div style={{position:'absolute',left:0,right:0,top:300,textAlign:'center',fontSize:40,fontWeight:950}}>{realLabel}</div>{flaws.slice(0,3).map((x,i)=><Bubble key={x+i} x={70+i*180} y={405+i*25} text={x} color={C.red} delay={i*8}/>)}</div><div style={{position:'absolute',right:210,top:250,width:650,height:560,borderRadius:44,background:'rgba(35,15,27,.72)',border:`3px solid ${C.pink}55`,boxShadow:`0 0 ${70*reveal}px ${C.pink}22`}}><div style={{position:'absolute',left:225,top:65,width:200,height:200,borderRadius:'50%',background:`radial-gradient(circle,${C.paper} 0%,${C.pink} 38%,transparent 72%)`,filter:'blur(1px)',opacity:.7+.3*Math.sin(f/18)}}/><div style={{position:'absolute',left:0,right:0,top:300,textAlign:'center',fontSize:40,fontWeight:950}}>{possibleLabel}</div>{dreams.slice(0,3).map((x,i)=><Bubble key={x+i} x={80+i*175} y={405-i*10} text={x} color={C.amber} delay={i*8}/>)}</div></Base>};
