import React from 'react';
export const K={paper:'#f3ede1',ink:'#15232c',gold:'#c8a15d',red:'#aa5754',teal:'#70a097',blue:'#5d7f96',green:'#6e8f73',orange:'#b47d55',gray:'#7c858b'};
export const q=(v:number)=>Math.max(0,Math.min(1,v));export const ease=(p:number)=>{const x=q(p);return x*x*(3-2*x)};
const T=({x=0,y=0,t,s=32,c=K.paper,a='middle',o=1}:{x?:number;y?:number;t:string;s?:number;c?:string;a?:'start'|'middle'|'end';o?:number})=><text x={x} y={y} textAnchor={a} fontFamily="Noto Sans JP,sans-serif" fontWeight={760} fontSize={s} fill={c} opacity={o}>{t}</text>;
const R=({x,y,w,h,c=K.paper,rx=18,o=1,stroke,sw=0}:{x:number;y:number;w:number;h:number;c?:string;rx?:number;o?:number;stroke?:string;sw?:number})=><rect x={x} y={y} width={w} height={h} rx={rx} fill={c} opacity={o} stroke={stroke} strokeWidth={sw}/>;
const labels:Record<string,string>={
'sato':'佐藤・37歳','clock-1745':'17:45','extra-project':'追加案件','trust-three':'任せられる／間違えない／断らない','month-stack':'翌月も、その翌月も','difficult-worker':'頼むと面倒','reward-work':'報酬＝次の仕事',
'calendar-three':'予定は3会議','broken-projector':'映らない','missing-copies':'資料不足','rookie-help':'新人フォロー','minutes':'議事録','invisible-work':'見えない仕事','ocb':'組織市民行動 OCB','gap-fill':'組織の隙間','thanks-to-duty':'善意 → 義務','citizenship-pressure':'citizenship pressure','fatigue':'citizenship fatigue','desk-overflow':'本来業務が埋もれる','everyone-points':'佐藤に頼もう',
'possible-load':'この仕事量は可能','record-120':'100 → 120','record-130':'120 → 130','ratchet':'ラチェット効果','new-minimum':'最高記録 → 最低ライン','target-up':'次回目標↑','output-hide':'成果を隠す','early-finish':'16時完成→18時送信','capacity-hide':'能力を隠した方が得','competency-trap':'能力の罠','sato-loop':'佐藤に頼む→経験→さらに頼む',
'idle-nine':'9人に余裕','busy-one':'1人だけ多忙','team-abcde':'A・B・C・D・E','urgent-four-hours':'残り4時間','choose-a':'Aへ集中','self-reinforce':'能力集中ループ','star-worker':'スター社員','jdr':'Job Demands–Resources','demands':'仕事要求','resources':'資源','eight-hours':'1日8時間','private-resource':'私生活から補填','hidden-overload':'過負荷が見えない',
'three-workers':'同じ仕事量','low-load':'低成果→仕事減','high-load':'高成果→仕事増','perverse-incentive':'逆向きのインセンティブ','factory-100':'100個→120個','factory-80':'80個→70個','exchange':'仕事↑なら何かも↑','plus-only':'足し算だけ','stop-helping':'もう助けない','knowledge-hide':'能力・知識を隠す','high-performance-punishment':'High-performance punishment',
'family-message':'今日も遅い？','expectation-growth':'期待の方が膨らむ','design-problem':'問題は制度設計','load-not-promotion':'昇進ではなく積載','elevator-load':'最大積載量','still-moving':'まだ動く','empty-desk':'翌朝の空席','hidden-jobs':'見えない仕事の山','who-does-it':'誰がやる？','trust-conversion':'信用→報酬 or 負担','asset-or-consumable':'資産 or 消耗品','final-question':'その机に何個？','nobody-shows':'能力を見せなくなる'
};
const tag=(k:string)=>labels[k]??k;
export const WorkSubject=({kind,p}:{kind:string;p:number})=>{const e=ease(p);
 if(['desk-overflow','month-stack','extra-project','hidden-jobs','elevator-load'].includes(kind))return <g><T y={-300} t={tag(kind)} s={42}/>{Array.from({length:7},(_,i)=><g key={i} opacity={q(e*1.5-i*.11)} transform={'translate('+(-300+i*82)+' '+(170-i*55)+')'}><R x={-120} y={-70} w={240} h={140} c={i>4?K.red:i%2?K.paper:'#b9c0bf'} stroke="#59646b" sw={5}/>{[0,1,2].map(j=><R key={j} x={-80} y={-35+j*30} w={120-j*10} h={8} c={K.gray}/>)}</g>)}</g>;
 if(['ratchet','new-minimum','record-120','record-130','target-up'].includes(kind))return <g><T y={-300} t={tag(kind)} s={42}/>{[0,1,2,3].map(i=><g key={i} transform={'translate('+(-300+i*200)+' '+(80-i*75)+')'}><circle r={75} fill="#263a45" stroke={i===3?K.red:K.gold} strokeWidth="12"/>{Array.from({length:8},(_,j)=>{const a=j*Math.PI/4;return <rect key={j} x={Math.cos(a)*78-10} y={Math.sin(a)*78-28} width="20" height="56" rx="4" fill={i===3?K.red:K.gold} transform={'rotate('+(a*180/Math.PI+90)+' '+Math.cos(a)*78+' '+Math.sin(a)*78+')'}/>})}</g>)}<path d={'M-360 240 L-80 130 L190 '+(70-90*e)+' L390 '+(-20-100*e)} fill="none" stroke={K.red} strokeWidth="15"/></g>;
 if(['everyone-points','choose-a','sato-loop','self-reinforce'].includes(kind))return <g><T y={-310} t={tag(kind)} s={42}/>{[-2,-1,0,1,2].map((i,j)=><circle key={i} cx={i*160} cy={j===2?40:160} r={j===2?72:52} fill={j===2?K.gold:K.gray}/>) }{[-2,-1,1,2].map((i,j)=><line key={i} x1={i*160} y1="120" x2={0} y2={45} stroke={K.red} strokeWidth="11" opacity={q(e*1.5-j*.14)}/>)}</g>;
 if(['jdr','demands','resources','private-resource','hidden-overload'].includes(kind))return <g><T y={-300} t={tag(kind)} s={40}/><line x1="0" y1="-180" x2="0" y2="180" stroke={K.paper} strokeWidth="16"/><line x1="-330" y1={-30+100*e} x2="330" y2={-30-100*e} stroke={K.gold} strokeWidth="18"/><rect x="-390" y="150" width="300" height="70" rx="18" fill={K.red}/><rect x="90" y="150" width="300" height="70" rx="18" fill={K.teal}/><T x={-240} y={198} t="要求" s={30}/><T x={240} y={198} t="資源" s={30}/></g>;
 if(['three-workers','low-load','high-load','perverse-incentive','factory-100','factory-80'].includes(kind))return <g><T y={-310} t={tag(kind)} s={40}/>{[0,1,2].map(i=><g key={i}><circle cx={-250+i*250} cy="-80" r="65" fill={i===2?K.gold:K.gray}/><R x={-320+i*250} y={10} w={140} h={170} c={i===2?K.teal:'#4e5a60'}/>{Array.from({length:2+i},(_,j)=><R key={j} x={-330+i*250} y={210+j*40} w={160} h={25} c={i===2?K.red:K.blue}/>)}</g>)}</g>;
 if(['exchange','plus-only','trust-conversion','asset-or-consumable'].includes(kind))return <g><T y={-300} t={tag(kind)} s={42}/><R x={-360} y={-160} w={300} h={330} c={K.red}/><R x={60} y={-160} w={300} h={330} c={K.teal}/><T x={-210} y={10} t="仕事・責任" s={30}/><T x={210} y={-10} t={kind==='plus-only'?'？':'報酬・裁量・休息'} s={kind==='plus-only'?58:24}/><line x1="-30" y1="0" x2="30" y2="0" stroke={K.gold} strokeWidth="14"/></g>;
 if(['output-hide','early-finish','capacity-hide','stop-helping','knowledge-hide','nobody-shows'].includes(kind))return <g><T y={-300} t={tag(kind)} s={40}/>{[0,1,2,3,4].map(i=><rect key={i} x={-350+i*150} y={180-(i+1)*75} width="105" height={(i+1)*75} rx="12" fill={i<2?K.gray:K.red} opacity={i<2?.5:q(1-e+i*.08)}/>) }<rect x="-400" y="230" width={800*e} height="80" fill="#08131b" opacity=".75"/></g>;
 if(['invisible-work','ocb','gap-fill','thanks-to-duty','citizenship-pressure','fatigue'].includes(kind))return <g><T y={-300} t={tag(kind)} s={40}/>{Array.from({length:9},(_,i)=>{const x=-320+(i%3)*320,y=-150+Math.floor(i/3)*170;return <g key={i} opacity={q(e*1.8-i*.08)}><R x={x-95} y={y-55} w={190} h={110} c={i===4?K.gold:i%2?K.teal:K.blue}/>{i!==4?<circle cx={x} cy={y} r="18" fill={K.paper}/>:<T x={x} y={y+10} t="佐藤" s={25}/>}</g>})}<path d="M-230 -95 L0 0 M230 -95 L0 0 M-230 75 L0 0 M230 75 L0 0 M-230 245 L0 0 M230 245 L0 0" stroke={K.red} strokeWidth="8" opacity={e}/></g>;
 if(['family-message','final-question','design-problem','reward-work','high-performance-punishment'].includes(kind))return <g><R x={-390} y={-230} w={780} h={460} c="#253a46" stroke={kind==='high-performance-punishment'?K.red:K.gold} sw={9}/><T y={-80} t={tag(kind)} s={44}/>{[0,1,2,3].map(i=><R key={i} x={-250} y={20+i*50} w={500-i*55} h={16} c={i===0?K.red:K.gray}/>)}</g>;
 return <g><R x={-360} y={-220} w={720} h={440} c="#263a45" stroke={kind.includes('trust')?K.gold:K.blue} sw={10}/><circle cx="-240" cy="-70" r="72" fill={kind.includes('trust')?K.gold:K.teal}/><T x={-120} y={-55} t={tag(kind)} s={36} a="start"/>{[0,1,2,3].map(i=><R key={i} x={-250} y={45+i*55} w={520-i*55} h={18} c={i===0?K.gold:K.gray} o={.8-i*.12}/>)}</g>;
};