import React from 'react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';

export type Beat={id:string;visual:string;narration:string;speech?:string};
const font='"Noto Sans CJK JP",sans-serif';
const C={paper:'#f1ecdf',muted:'#9ba4ac',red:'#b85550',blue:'#5f92ba',cyan:'#6eb4c4',amber:'#d7a84c',green:'#7da27a',ink:'#071016',violet:'#8a7db0'};
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const beatNo=(id:string)=>Number(id.replace(/\D/g,''))||0;

const Dust=()=>{const f=useCurrentFrame();return <>{Array.from({length:44},(_,i)=><div key={i} style={{position:'absolute',left:(i*173+Math.sin((f+i*13)/75)*34)%1920,top:(i*107+f*.11)%1080,width:2+(i%3),height:2+(i%3),borderRadius:20,background:'rgba(241,236,223,.26)',opacity:.06+(i%6)*.018}}/>)}</>};
const Shell=({children,tone='night'}:{children:React.ReactNode;tone?:'night'|'blue'|'warm'|'paper'|'black'})=>{const f=useCurrentFrame();const bg=tone==='blue'?'linear-gradient(145deg,#061019,#0f2a39 56%,#030506)':tone==='warm'?'linear-gradient(145deg,#160d09,#332219 55%,#040404)':tone==='paper'?'linear-gradient(145deg,#151410,#27231c 55%,#070707)':tone==='black'?'#020304':'linear-gradient(145deg,#05070a,#12171c 57%,#030405)';return <AbsoluteFill style={{background:bg,color:C.paper,overflow:'hidden'}}><AbsoluteFill style={{transform:`scale(${1.01+Math.sin(f/160)*.006})`}}>{children}</AbsoluteFill><Dust/><AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,transparent 28%,rgba(0,0,0,.28) 72%,rgba(0,0,0,.8) 100%)'}}/></AbsoluteFill>};
const Title=({children,sub}:{children:React.ReactNode;sub?:string})=><div style={{position:'absolute',left:108,top:72,fontFamily:font,fontWeight:950,fontSize:50,letterSpacing:1.1,textShadow:'0 4px 28px rgba(0,0,0,.78)'}}>{children}{sub&&<div style={{fontSize:22,color:C.muted,marginTop:10,fontWeight:650}}>{sub}</div>}</div>;
const Card=({x,y,w=300,h=180,children,border='rgba(241,236,223,.16)',bg='rgba(7,12,17,.72)'}:{x:number;y:number;w?:number;h?:number;children:React.ReactNode;border?:string;bg?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:h,borderRadius:28,border:`2px solid ${border}`,background:bg,boxShadow:'0 20px 70px rgba(0,0,0,.25)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:font}}>{children}</div>;
const Candidate=({x,y,label,color,score,scale=1}:{x:number;y:number;label:string;color:string;score?:string;scale?:number})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,transform:`scale(${scale}) translateY(${Math.sin((f+x)/45)*4}px)`,transformOrigin:'50% 100%',fontFamily:font,textAlign:'center'}}><div style={{width:120,height:120,borderRadius:'50%',background:`radial-gradient(circle at 40% 32%,${color},#111 74%)`,border:`6px solid ${color}`,boxShadow:`0 0 40px ${color}44`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:62,fontWeight:950}}>{label}</div>{score&&<div style={{marginTop:16,fontSize:36,fontWeight:950,color}}>{score}</div>}</div>};
const RankingCard=({x,y,count,rows,color}:{x:number;y:number;count:number;rows:string[];color:string})=>{const f=useCurrentFrame();const p=interpolate(f,[0,28],[0,1],clamp);return <div style={{position:'absolute',left:x,top:y,width:430,height:460,borderRadius:34,border:`2px solid ${color}66`,background:'rgba(5,10,14,.76)',padding:'30px 34px',fontFamily:font,opacity:p,transform:`translateY(${(1-p)*26}px)`}}><div style={{fontSize:48,fontWeight:950,color,marginBottom:28}}>{count}人</div>{rows.map((r,i)=><div key={r} style={{fontSize:40,fontWeight:850,margin:'20px 0',display:'flex',gap:18}}><span style={{color:C.muted,width:72}}>{i+1}位</span><span>{r}</span></div>)}</div>};
const VoteBar=({x,y,label,value,max=70,color}:{x:number;y:number;label:string;value:number;max?:number;color:string})=>{const f=useCurrentFrame();const w=interpolate(f,[8,48],[0,(value/max)*900],clamp);return <div style={{position:'absolute',left:x,top:y,fontFamily:font}}><div style={{display:'flex',alignItems:'center',gap:18}}><div style={{fontSize:44,fontWeight:950,width:70,color}}>{label}</div><div style={{width:920,height:58,borderRadius:32,background:'rgba(255,255,255,.07)',overflow:'hidden'}}><div style={{width:w,height:'100%',background:color,boxShadow:`0 0 26px ${color}66`}}/></div><div style={{fontSize:42,fontWeight:950,minWidth:120,textAlign:'right'}}>{value}票</div></div></div>};
const Tag=({x,y,text,color=C.cyan,delay=0}:{x:number;y:number;text:string;color?:string;delay?:number})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+24],[0,1],clamp);return <div style={{position:'absolute',left:x,top:y,padding:'13px 22px',borderRadius:18,border:`2px solid ${color}66`,background:'rgba(4,8,12,.78)',fontFamily:font,fontWeight:900,fontSize:29,color,opacity:p,transform:`translateY(${(1-p)*18}px) scale(${.94+.06*p})`}}>{text}</div>};
const Ballot=({x,y,text,rotate=0,color=C.paper}:{x:number;y:number;text:string;rotate?:number;color?:string})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:x,top:y,width:360,height:180,background:'#e8e3d8',color:'#12171a',borderRadius:12,boxShadow:'0 18px 45px rgba(0,0,0,.35)',transform:`rotate(${rotate+Math.sin((f+x)/75)*1.2}deg)`,padding:'30px 34px',fontFamily:font,fontSize:34,fontWeight:900,borderTop:`10px solid ${color}`}}>{text}</div>};
const Arrow=({x,y,w,angle,color=C.amber}:{x:number;y:number;w:number;angle:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:8,background:color,transform:`rotate(${angle}deg)`,transformOrigin:'0 50%',boxShadow:`0 0 18px ${color}55`}}><div style={{position:'absolute',right:-2,top:-9,width:0,height:0,borderTop:'13px solid transparent',borderBottom:'13px solid transparent',borderLeft:`22px solid ${color}`}}/></div>;
const SeatGrid=({x,y,red,blue,other=0}:{x:number;y:number;red:number;blue:number;other?:number})=>{const total=red+blue+other;return <div style={{position:'absolute',left:x,top:y,width:680,display:'grid',gridTemplateColumns:'repeat(10, 54px)',gap:12}}>{Array.from({length:total},(_,i)=>{const color=i<red?C.red:i<red+blue?C.blue:C.violet;return <div key={i} style={{width:54,height:54,borderRadius:'50% 50% 12px 12px',background:color,boxShadow:`0 0 18px ${color}44`}}/>})}</div>};

const IntroRankings=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);return <Shell tone="blue"><Title>{p===1?'100人の民意を、一人の勝者にする':'同じ100人、3つの順位'}</Title>{p===1?<><Candidate x={430} y={370} label="A" color={C.red} scale={1.25}/><Candidate x={900} y={370} label="B" color={C.amber} scale={1.25}/><Candidate x={1370} y={370} label="C" color={C.blue} scale={1.25}/><Tag x={690} y={720} text="有権者 100人" color={C.paper}/></>:<><RankingCard x={160} y={270} count={35} rows={['A','B','C']} color={C.red}/><RankingCard x={745} y={270} count={33} rows={['B','C','A']} color={C.amber}/><RankingCard x={1330} y={270} count={32} rows={['C','A','B']} color={C.blue}/></>}</Shell>};

const FirstPastPost=()=> <Shell><Title>1位票だけ数えると</Title><VoteBar x={330} y={300} label="A" value={35} color={C.red}/><VoteBar x={330} y={470} label="B" value={33} color={C.amber}/><VoteBar x={330} y={640} label="C" value={32} color={C.blue}/><Tag x={760} y={820} text="A が勝者" color={C.red}/></Shell>;

const HeadToHead=()=>{const f=useCurrentFrame();const move=interpolate(f,[20,70],[0,1],clamp);return <Shell tone="black"><Title>A vs C にすると、勝者が変わる</Title><Candidate x={360} y={350} label="A" color={C.red} score="35票" scale={1.35}/><Candidate x={1420} y={350} label="C" color={C.blue} score="65票" scale={1.35}/><div style={{position:'absolute',left:760,top:310,fontFamily:font,fontSize:38,fontWeight:900,color:C.amber}}>Bを1位にした33人</div>{Array.from({length:11},(_,i)=>{const sx=790+(i%6)*55,sy=420+Math.floor(i/6)*70;const tx=1370+(i%4)*45,ty=600+Math.floor(i/4)*44;return <div key={i} style={{position:'absolute',left:interpolate(move,[0,1],[sx,tx]),top:interpolate(move,[0,1],[sy,ty]),width:24,height:24,borderRadius:'50%',background:C.amber,boxShadow:`0 0 16px ${C.amber}55`}}/>})}<Arrow x={970} y={570} w={320} angle={0} color={C.amber}/><Tag x={720} y={760} text="2位だったCへ移る" color={C.amber}/></Shell>};

const Cycle=()=>{const f=useCurrentFrame();const pulse=.85+.15*Math.sin(f/20);return <Shell><Title>集団の好みは「じゃんけん」になる</Title><Candidate x={840} y={240} label="A" color={C.red}/><Candidate x={430} y={660} label="B" color={C.amber}/><Candidate x={1260} y={660} label="C" color={C.blue}/><Arrow x={760} y={370} w={430} angle={135} color={C.red}/><Arrow x={610} y={700} w={690} angle={0} color={C.amber}/><Arrow x={1330} y={665} w={440} angle={-135} color={C.blue}/><div style={{position:'absolute',left:780,top:525,fontFamily:font,fontSize:54,fontWeight:950,transform:`scale(${pulse})`}}>A &gt; B &gt; C &gt; A</div><Tag x={720} y={815} text="コンドルセのパラドックス" color={C.violet}/></Shell>};

const MeasuringWill=()=>{const f=useCurrentFrame();return <Shell tone="paper"><Title>投票箱は「民意の温度計」なのか？</Title><div style={{position:'absolute',left:330,top:270,width:220,height:530,border:'12px solid rgba(241,236,223,.3)',borderRadius:120}}><div style={{position:'absolute',left:78,bottom:40,width:64,height:interpolate(Math.sin(f/45),[-1,1],[130,410]),borderRadius:40,background:C.red}}/><div style={{position:'absolute',left:54,bottom:-32,width:112,height:112,borderRadius:'50%',background:C.red}}/></div><Ballot x={830} y={330} text="A 35 / B 33 / C 32" color={C.red}/><Ballot x={930} y={570} text="A 35 / C 65" rotate={-3} color={C.blue}/><Tag x={1200} y={760} text="同じ民意、違う答え" color={C.amber}/></Shell>};

const RuleMachine=()=>{const f=useCurrentFrame();const x=interpolate(f%180,[0,179],[220,1450]);return <Shell tone="blue"><Title>選挙制度は「民意 → 答え」の変換機</Title><Ballot x={x-180} y={430} text="100人の好み" rotate={-2}/><div style={{position:'absolute',left:760,top:300,width:460,height:430,borderRadius:50,border:'3px solid rgba(110,180,196,.42)',background:'rgba(6,19,27,.75)',fontFamily:font,display:'flex',alignItems:'center',justifyContent:'center',fontSize:58,fontWeight:950,color:C.cyan}}>集計ルール</div>{[0,1,2].map(i=><div key={i} style={{position:'absolute',left:830+i*115,top:450+(i%2)*80,width:105,height:105,border:`8px dotted ${i===1?C.amber:C.cyan}`,borderRadius:'50%',transform:`rotate(${f*(i%2?1:-1)}deg)`}}/>)}<Candidate x={1530} y={470} label="?" color={C.amber}/></Shell>};

const FairnessConditions=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);const items=p===8?['歪めない','誰でも納得','一つの勝者']:['全員一致を尊重','独裁者なし','無関係なCで逆転しない'];return <Shell><Title>{p===8?'「完璧なルール」を作ればいい？':'公平なら、これくらい守ってほしい'}</Title>{items.map((t,i)=><Card key={t} x={190+i*570} y={360} w={460} h={280} border={[C.green,C.amber,C.cyan][i]+'77'}><div style={{fontSize:40,fontWeight:950,textAlign:'center',padding:30,color:[C.green,C.amber,C.cyan][i]}}>{t}</div></Card>)}<Tag x={720} y={760} text="どれも常識的に見える" color={C.paper}/></Shell>};

const ArrowScene=()=>{const f=useCurrentFrame();return <Shell tone="black"><Title>1951 — Kenneth Arrow</Title><div style={{position:'absolute',left:260,top:250,width:520,height:600,borderRadius:260,background:'radial-gradient(circle at 48% 32%,#67645e,#111 70%)',border:'2px solid rgba(241,236,223,.15)'}}/><div style={{position:'absolute',left:930,top:300,fontFamily:font,fontSize:46,lineHeight:1.9,fontWeight:850}}><div>個人の順位</div><div style={{color:C.muted}}>↓</div><div>社会全体の順位</div><div style={{color:C.muted}}>↓</div><div style={{color:C.amber,fontSize:66}}>公平な変換は可能か？</div></div><div style={{position:'absolute',left:220,top:800,fontFamily:font,fontSize:34,color:C.muted}}>社会選択理論</div><div style={{position:'absolute',right:250,top:720,fontFamily:font,fontSize:90,fontWeight:950,opacity:.08,transform:`translateX(${Math.sin(f/60)*10}px)`}}>→</div></Shell>};

const Impossibility=({beat}:{beat:Beat})=>{const f=useCurrentFrame();const p=beatNo(beat.id);return <Shell tone="black"><Title>{p===11?'「見つからない」ではなく「存在しない」':'ルールを決めた瞬間、公平の意味が決まる'}</Title><div style={{position:'absolute',left:410,top:290,width:520,height:520,borderRadius:'50%',border:`8px solid ${C.red}99`,transform:`translateX(${Math.sin(f/40)*8}px)`}}/><div style={{position:'absolute',left:750,top:290,width:520,height:520,borderRadius:'50%',border:`8px solid ${C.blue}99`,transform:`translateX(${-Math.sin(f/40)*8}px)`}}/><div style={{position:'absolute',left:1090,top:290,width:520,height:520,borderRadius:'50%',border:`8px solid ${C.amber}99`}}/><div style={{position:'absolute',left:560,top:470,fontFamily:font,fontSize:42,fontWeight:950,color:C.red}}>公平A</div><div style={{position:'absolute',left:900,top:470,fontFamily:font,fontSize:42,fontWeight:950,color:C.blue}}>公平B</div><div style={{position:'absolute',left:1240,top:470,fontFamily:font,fontSize:42,fontWeight:950,color:C.amber}}>公平C</div><div style={{position:'absolute',left:700,top:665,fontFamily:font,fontSize:74,fontWeight:950,color:C.paper}}>全部同時は無理</div></Shell>};

const TripChoice=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);return <Shell tone="warm"><Title>{p===12?'修学旅行なら、もっと分かりやすい':'「一番人気」と「一番納得」は同じか？'}</Title><Card x={160} y={300} w={470} h={390} border={C.red+'77'}><div style={{textAlign:'center'}}><div style={{fontSize:58,fontWeight:950}}>東京</div><div style={{fontSize:88,fontWeight:950,color:C.red}}>10</div></div></Card><Card x={725} y={300} w={470} h={390} border={C.amber+'77'}><div style={{textAlign:'center'}}><div style={{fontSize:58,fontWeight:950}}>北海道</div><div style={{fontSize:88,fontWeight:950,color:C.amber}}>9</div></div></Card><Card x={1290} y={300} w={470} h={390} border={C.blue+'77'}><div style={{textAlign:'center'}}><div style={{fontSize:58,fontWeight:950}}>沖縄</div><div style={{fontSize:88,fontWeight:950,color:C.blue}}>11</div></div></Card>{p===13&&<><Arrow x={970} y={740} w={-1} angle={180}/><Tag x={515} y={760} text="北海道派9人の第2希望 → 東京" color={C.amber}/><Tag x={1090} y={760} text="東京なら19人が納得" color={C.green}/></>}</Shell>};

const FairnessTradeoff=()=> <Shell><Title>「公平」には、複数の意味がある</Title>{[['熱烈な1位票',C.red],['広く嫌われない',C.green],['少数派を残す',C.blue],['多数派を反映',C.amber]].map(([t,c],i)=><Card key={t} x={150+(i%2)*850} y={250+Math.floor(i/2)*330} w={700} h={250} border={(c as string)+'77'}><div style={{fontSize:44,fontWeight:950,color:c as string}}>{t}</div></Card>)}<div style={{position:'absolute',left:785,top:465,fontFamily:font,fontSize:110,fontWeight:950,color:C.paper}}>VS</div></Shell>;

const DistrictMajority=()=>{const f=useCurrentFrame();return <Shell tone="blue"><Title>60対40なのに、議席は10対0になる</Title><div style={{position:'absolute',left:140,top:260,width:920,display:'grid',gridTemplateColumns:'repeat(5, 160px)',gap:24}}>{Array.from({length:10},(_,i)=><div key={i} style={{height:190,borderRadius:24,border:'2px solid rgba(241,236,223,.12)',background:'rgba(4,8,12,.58)',padding:18,fontFamily:font}}><div style={{fontSize:22,color:C.muted}}>選挙区 {i+1}</div><div style={{height:32,marginTop:34,borderRadius:20,overflow:'hidden',display:'flex'}}><div style={{width:'60%',background:C.red}}/><div style={{width:'40%',background:C.blue}}/></div><div style={{marginTop:18,fontSize:28,fontWeight:950}}><span style={{color:C.red}}>60</span> : <span style={{color:C.blue}}>40</span></div></div>)}</div><div style={{position:'absolute',right:170,top:350,fontFamily:font,textAlign:'center'}}><div style={{fontSize:34,color:C.muted}}>議席</div><div style={{fontSize:150,fontWeight:950,color:C.red,transform:`scale(${.98+.02*Math.sin(f/20)})`}}>10</div><div style={{fontSize:44,fontWeight:950}}>対</div><div style={{fontSize:150,fontWeight:950,color:C.blue}}>0</div></div></Shell>};

const Proportional=()=> <Shell><Title>票をそのまま議席に近づけると</Title><div style={{position:'absolute',left:220,top:280,fontFamily:font,fontSize:48,fontWeight:950}}><span style={{color:C.red}}>赤党 60%</span><span style={{margin:'0 28px',color:C.muted}}>→</span><span style={{color:C.red}}>6議席</span></div><div style={{position:'absolute',left:220,top:390,fontFamily:font,fontSize:48,fontWeight:950}}><span style={{color:C.blue}}>青党 40%</span><span style={{margin:'0 28px',color:C.muted}}>→</span><span style={{color:C.blue}}>4議席</span></div><SeatGrid x={640} y={560} red={6} blue={4}/><Tag x={320} y={720} text="少数派も議席を持てる" color={C.green}/><Tag x={1130} y={720} text="ただし政党が細かく分かれることも" color={C.amber}/></Shell>;

const JapanTransition=()=>{const f=useCurrentFrame();const pts=[[890,270],[850,345],[910,420],[865,500],[810,575],[760,650],[690,730],[620,790],[550,825],[470,850]];return <Shell tone="black"><Title>ここで、日本の選挙制度を見る</Title>{pts.map(([x,y],i)=><div key={i} style={{position:'absolute',left:x+Math.sin((f+i*8)/55)*7,top:y,width:55-i*2,height:55-i*2,borderRadius:'50%',background:i<4?C.paper:C.cyan,opacity:.7,boxShadow:'0 0 28px rgba(110,180,196,.25)'}}/>)}<div style={{position:'absolute',left:1040,top:370,fontFamily:font,fontSize:170,fontWeight:950,letterSpacing:20}}>日本</div><div style={{position:'absolute',left:1050,top:600,fontFamily:font,fontSize:40,color:C.muted}}>衆議院選挙は「二つの公平」を同時に扱う</div></Shell>};

const JapanBallots=()=> <Shell tone="paper"><Title>なぜ投票用紙を二枚書くのか</Title><Ballot x={340} y={330} text="小選挙区\n候補者名を書く" rotate={-4} color={C.red}/><Ballot x={1090} y={330} text="比例代表\n政党名を書く" rotate={4} color={C.blue}/><Tag x={390} y={620} text="地域の代表" color={C.red}/><Tag x={1160} y={620} text="政党への支持" color={C.blue}/><Arrow x={810} y={480} w={270} angle={0} color={C.amber}/></Shell>;

const SmallDistrict=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);return <Shell tone="warm"><Title>{p===19?'小選挙区が守っているもの':'小選挙区が捨てるもの'}</Title><div style={{position:'absolute',left:230,top:290,width:760,height:520,borderRadius:40,border:'3px solid rgba(241,236,223,.16)',background:'rgba(5,8,10,.5)'}}>{Array.from({length:30},(_,i)=><div key={i} style={{position:'absolute',left:50+(i%6)*110,top:50+Math.floor(i/6)*85,width:28,height:28,borderRadius:'50%',background:i<17?C.red:C.blue}}/>)}</div><Arrow x={1030} y={550} w={260} angle={0} color={C.amber}/><div style={{position:'absolute',right:250,top:390,width:240,height:300,borderRadius:'50% 50% 20% 20%',background:p===19?C.red:C.muted,boxShadow:'0 0 60px rgba(184,85,80,.25)'}}/><div style={{position:'absolute',right:220,top:735,fontFamily:font,fontSize:42,fontWeight:950,color:p===19?C.red:C.muted}}>{p===19?'勝者 1人':'敗者票 → 0議席'}</div></Shell>};

const ProportionalJapan=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);return <Shell tone="blue"><Title>{p===21?'比例代表が守っているもの':'比例代表の別の弱点'}</Title><div style={{position:'absolute',left:220,top:320,width:560,fontFamily:font}}>{[['A党',42,C.red],['B党',31,C.blue],['C党',17,C.amber],['D党',10,C.violet]].map(([n,v,c])=><div key={n as string} style={{marginBottom:34}}><div style={{fontSize:30,fontWeight:900}}>{n as string} <span style={{color:c as string}}>{v as number}%</span></div><div style={{height:28,borderRadius:20,background:'rgba(255,255,255,.07)',overflow:'hidden'}}><div style={{width:`${Number(v)*2.2}%`,height:'100%',background:c as string}}/></div></div>)}</div><SeatGrid x={980} y={390} red={8} blue={6} other={6}/><Tag x={1030} y={700} text={p===21?'得票を議席に近づける':'政党が細かく分かれることも'} color={p===21?C.green:C.amber}/></Shell>};

const Hybrid=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);return <Shell><Title>{p===23?'日本は二つの方式を「並立」させる':'完璧だから混ぜたのではない'}</Title><Card x={180} y={310} w={650} h={370} border={C.red+'77'}><div style={{textAlign:'center'}}><div style={{fontSize:48,fontWeight:950,color:C.red}}>小選挙区</div><div style={{fontSize:30,marginTop:30}}>勝者をはっきり</div><div style={{fontSize:28,color:C.muted,marginTop:20}}>地域の代表</div></div></Card><Card x={1090} y={310} w={650} h={370} border={C.blue+'77'}><div style={{textAlign:'center'}}><div style={{fontSize:48,fontWeight:950,color:C.blue}}>比例代表</div><div style={{fontSize:30,marginTop:30}}>得票を議席へ</div><div style={{fontSize:28,color:C.muted,marginTop:20}}>少数派を残す</div></div></Card><div style={{position:'absolute',left:875,top:450,fontFamily:font,fontSize:82,fontWeight:950,color:C.amber}}>＋</div><Tag x={650} y={760} text={p===23?'違う公平を同時に扱う':'違う欠点を組み合わせる'} color={C.amber}/></Shell>};

const UpperHouse=()=>{const f=useCurrentFrame();return <Shell tone="paper"><Title>参議院も、一種類の選び方ではない</Title><div style={{position:'absolute',left:310,top:250,width:1300,height:560,borderRadius:'50% 50% 20% 20%',border:'4px solid rgba(241,236,223,.18)',transform:`scale(${1+.008*Math.sin(f/36)})`}}>{Array.from({length:42},(_,i)=>{const a=(Math.PI*.15)+(i/41)*Math.PI*.7;const row=i%2;const x=630+Math.cos(a)*(470-row*90);const y=380+Math.sin(a)*(310-row*70);return <div key={i} style={{position:'absolute',left:x,top:y,width:34,height:34,borderRadius:'50%',background:i%3===0?C.blue:i%3===1?C.red:C.amber}}/>})}</div><Tag x={430} y={760} text="選挙区" color={C.red}/><Tag x={1160} y={760} text="比例代表" color={C.blue}/></Shell>};

const Tradeoffs=()=> <Shell><Title>複雑さは「失敗」ではなく、トレードオフの痕跡</Title>{[['政権の選びやすさ',78,C.red],['少数派の反映',70,C.blue],['地域代表',64,C.amber],['得票と議席の近さ',74,C.green]].map(([n,v,c],i)=><div key={n as string} style={{position:'absolute',left:300,top:290+i*145,width:1320,fontFamily:font}}><div style={{fontSize:30,fontWeight:900,marginBottom:14}}>{n as string}</div><div style={{height:28,borderRadius:20,background:'rgba(255,255,255,.07)'}}><div style={{width:`${v}%`,height:'100%',borderRadius:20,background:c as string}}/></div></div>)}</Shell>;

const PolicyChoices=({beat}:{beat:Beat})=>{const p=beatNo(beat.id);const labels=p===27?['小選挙区を増やす','比例代表を増やす','区割りを変える','議席配分を変える']:['政権を選びやすく','少数派を残す','地域代表を作る','得票率を議席へ'];return <Shell tone="blue"><Title>{p===27?'本当に問うべきは「どれが公平？」ではない':'この制度は、何を優先しているのか'}</Title>{labels.map((t,i)=><Card key={t} x={170+(i%2)*850} y={260+Math.floor(i/2)*300} w={700} h={220} border={[C.red,C.blue,C.amber,C.green][i]+'66'}><div style={{fontSize:38,fontWeight:950,textAlign:'center',color:[C.red,C.blue,C.amber,C.green][i]}}>{t}</div></Card>)}<Tag x={710} y={805} text="そして、何を諦めるのか" color={C.paper}/></Shell>};

const BallotBox=()=>{const f=useCurrentFrame();return <Shell tone="black"><Title>政治は、投票箱より前から始まっている</Title><div style={{position:'absolute',left:700,top:400,width:520,height:370,background:'#17191a',border:'5px solid rgba(241,236,223,.25)',borderRadius:30,boxShadow:'0 30px 80px rgba(0,0,0,.5)'}}><div style={{position:'absolute',left:120,top:-24,width:280,height:30,borderRadius:20,background:'#010203'}}/></div>{['候補者をどう選ぶ','票をどう数える','1位だけ見る？','議席へどう変換？'].map((t,i)=>{const x=180+i*390;const y=230+Math.sin((f+i*11)/38)*9;return <div key={t} style={{position:'absolute',left:x,top:y,fontFamily:font,fontSize:28,fontWeight:900,color:[C.red,C.blue,C.amber,C.green][i]}}>{t}<Arrow x={80} y={55} w={350} angle={Math.atan2(430-y,920-x)*180/Math.PI} color={[C.red,C.blue,C.amber,C.green][i]}/></div>})}</Shell>};

const Ending=()=>{const f=useCurrentFrame();const drop=(offset:number)=>interpolate((f-offset)%160,[0,100],[260,650],clamp);return <Shell tone="paper"><Title>民主主義は「完璧」を選ぶ制度ではない</Title><Ballot x={420} y={drop(0)} text="小選挙区" rotate={-6} color={C.red}/><Ballot x={1120} y={drop(48)} text="比例代表" rotate={6} color={C.blue}/><div style={{position:'absolute',left:690,top:720,width:560,height:240,background:'#17191a',border:'4px solid rgba(241,236,223,.22)',borderRadius:28}}/><div style={{position:'absolute',left:470,top:280,fontFamily:font,fontSize:58,fontWeight:950,textAlign:'center',width:980}}>どの不完全さを、社会として引き受けるか</div><Tag x={705} y={835} text="公平とは何か？" color={C.amber}/></Shell>};

const scenes:Record<string,(beat:Beat)=>React.ReactNode>={
  intro_rankings:(b)=><IntroRankings beat={b}/>,
  first_past_post:()=> <FirstPastPost/>,
  head_to_head:()=> <HeadToHead/>,
  cycle:()=> <Cycle/>,
  measuring_will:()=> <MeasuringWill/>,
  rule_machine:()=> <RuleMachine/>,
  fairness_conditions:(b)=><FairnessConditions beat={b}/>,
  arrow:()=> <ArrowScene/>,
  impossibility:(b)=><Impossibility beat={b}/>,
  trip_choice:(b)=><TripChoice beat={b}/>,
  fairness_tradeoff:()=> <FairnessTradeoff/>,
  district_majority:()=> <DistrictMajority/>,
  proportional:()=> <Proportional/>,
  japan_transition:()=> <JapanTransition/>,
  japan_ballots:()=> <JapanBallots/>,
  small_district:(b)=><SmallDistrict beat={b}/>,
  proportional_japan:(b)=><ProportionalJapan beat={b}/>,
  hybrid:(b)=><Hybrid beat={b}/>,
  upper_house:()=> <UpperHouse/>,
  tradeoffs:()=> <Tradeoffs/>,
  policy_choices:(b)=><PolicyChoices beat={b}/>,
  ballot_box:()=> <BallotBox/>,
  ending:()=> <Ending/>
};
export const SUPPORTED_VISUALS=Object.keys(scenes);
export const RichScene=({beat}:{beat:Beat})=>{const renderer=scenes[beat.visual];if(!renderer)throw new Error(`Unsupported V31 visual: ${beat.visual} for ${beat.id}`);return <>{renderer(beat)}</>;};
